### ISSUE TITLE
Checker Framework Eclipse Plug-In Conflicting Handlers Error

### ISSUE THREAD

**Issue by monitorlizard** [typetools/checker-framework#1015]
On a fresh installation of Eclipse 4.6.2 (on Windows) and Checker Framework 2.1.8 the following error message appears when starting Eclipse:

`Conflicting handlers for checkers.eclipse.runlock: {org.checkerframework.eclipse.actions.CheckerActions$LockAction} vs {org.checkerframework.eclipse.actions.CheckerActions$IndexAction}`

The framework then doesn't work in consequence...

**Comment by mernst** [comment]
Thanks for pointing out the problem, and sorry about that.
I have fixed it via commit  e9a7697.

**Comment by mernst** [comment]
We weren't able to reproduce the error on a fresh Eclipse installation.
I speculate that perhaps you were having a problem upgrading an existing Eclipse that already had a prior version of the Checker Framework plugin installed.  Is that correct?
If so, a workaround for this bug is to use a fresh Eclipse.

**Comment by monitorlizard** [comment]
No! Fresh Windows 7 installation, newly downloaded eclipse, newly installed Checker Framework

**Comment by wmdietl** [comment]
@monitorlizard  Did you try with the fix in https://github.com/typetools/checker-framework/commit/e9a7697f2ab2cb49b5e92dc3a11882bc3e7099ee ?

@mernst Did you try reproducing before or after that commit?

**Comment by monitorlizard** [comment]
No, I did not test any fix. I tried release 2.1.8.
