### ISSUE TITLE
Index Checker does not track relationships between arbitrary variables

### ISSUE THREAD

**Issue by Bohdankm22** [typetools/checker-framework#1157]
Consider this code:

```
private static void readInfo(String k, int m) {
        String[] parts = k.split(" ");
        // Ex. 1
        if (parts.length >= m && m >= 6) {
            Integer.parseInt(parts[1]);     // Potentially unsafe array access: the index could be larger than the arrays bound
        }
        // Ex. 2
        if (m >= 6 && parts.length >= m) {
            Integer.parseInt(parts[1]);     // Potentially unsafe array access: the index could be larger than the arrays bound
        }
        // Ex. 3
        if (m > 6) {
            if (parts.length >= m) {
                Integer.parseInt(parts[1]);    // Potentially unsafe array access: the index could be larger than the arrays bound
            }
        }
    }
```

All three examples above check that:
1. the array length is bigger than the variable "m" 
2. the variable "m" is greater than some value (in example 6).

However, all three scenarios lead to the error when trying to access the array.
```
Error:(120, 36) java: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
  found   : @UpperBoundUnknown int
  required: an integer less than parts's length (@LTLengthOf("parts"))
```

Expected result: the array could be accessed all the indexes that less than the variable.

**Comment by mernst** [comment]
Thanks for the report.
I confirm all of these problems:  the Index Checker is not able to make the necessary inferences, so each of these is a false positive warning.  If the Index Checker tracked symbolic relationships among arbitrary pairs of variables, it could avoid issuing these false positive warnings.

Did these examples come up in real-world code?

I'm inclined to leave the behavior as it currently is.  Every type system aims to report as few false positives as possible, but every type system also has a limited set of abstractions, which is what makes it simple to use and fast to run.  New abstractions and reasoning capabilities must be added on a case-by-case basis.

When we learn of multiple real-world examples that have the same underlying root cause as these examples, then we should re-open this issue and add the necessary abstractions and code.
