### ISSUE TITLE
javac shows null as incompatibe type

### ISSUE THREAD

**Issue by shivanshsoni** [typetools/checker-framework#1185]
my code:

abstract class checker<R>
{
	R r;
	void checker4()
	{
		r=null;
		int i=0;
	}
System.out.println(i+1);
}

Output :
![screenshot 19](https://cloud.githubusercontent.com/assets/24546371/24327806/d917b396-11f7-11e7-9141-b97435e98d4c.png)

the current version of checker-framework:  2.1.9

**Comment by mernst** [comment]
Please do not attach a screenshot.  Instead, cut and paste the error message.  That is more readable, and it is searchable too.  Furthermore, it won't include irrelevant information from previous commands, as your screenshot does.

In addition, make sure your bug report is complete.  I cannot compile your code because there is no definition of the `R` class that it references.  Therefore, I cannot confirm the problem nor analyze it.

**Comment by mernst** [comment]
I'm closing this issue, because it is incomplete and I requested the code over a week ago.
