### ISSUE TITLE
Defaults for unchecked code in the Value Checker

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#1303]
The Value Checker issues warnings when run on `checker/tests/signedness-unchecked-defaults/TestUncheckedByteCode.java` because it uses conservative defaulting for unchecked code. This might not be the correct behavior for the Value Checker, since it's not intended to be run as a verification tool. Instead, it would be better to be conservative about issuing warnings and allow the later analysis to issue warnings.

**Comment by wmdietl** [comment]
I'm not sure what you mean with `might not be the correct behavior for the Value Checker, since it's not intended to be run as a verification tool`.
The Value Checker should give a sound approximation of the runtime value, which downstream analyses can then rely upon for their own decisions.
As mentioned in #1301, what should be done is adapt the defaults for unchecked code. For the Value Checker it makes sense to use the largest range supported by the underlying type, for both parameters and return types.

**Comment by smillst** [comment]
We agreed to do as Werner suggested:
> Use the largest range supported by the underlying type, for both parameters and return types.
