### ISSUE TITLE
Fix for "Unhandled Token in @SuppressWarnings" in Eclipse

### ISSUE THREAD

**Issue by digulla** [typetools/checker-framework#1367]
Add a checker which takes a list of valid warnings from one or more files.
When processing annotations, check the values against the file contents. Issue warnings as necessary.
The check framework should come with a predefined set of files for common warning sets like JDK, Eclipse, SonarCube (or whatever they call themselves ATM), etc.

That would allow to disable the warning in Eclipse and still catch typos.

**Comment by wmdietl** [comment]
Could you please provide a few more details about what problem you're running into and what changes you are proposing?

**Comment by mernst** [comment]
The Checker Framework manual already tells you two ways to suppress the "Unhandled Token in @SuppressWarnings"; see the section titled "Troubleshooting Eclipse" (https://checkerframework.org/manual/#eclipse-troubleshooting).

The problem is that disabling the Eclipse warnings -- though it will eliminate many annoying false positive Eclipse notifications -- might also eliminate some true positive Eclipse notifications.

I think you are suggesting writing a new checker, to be distributed with the Checker Framework, that issues a warning whenever the key in a `@SuppressWarnings(...)` annotation does not appear on a whitelist.

This sounds like a good feature to build into Eclipse.  That is a more natural location for the functionality, and each tool designer could register their tool's warning keys.

If you wanted to write such a checker nonetheless, it would be easy to write.  Collecting all the possible warning keys would be the most challenging part.

**Comment by digulla** [comment]
I have some ideas how to collect the keys automatically (scraping source code). My suggestion is that you provide a checker out of the box for typos in `@SuppressWarnings` which accepts two kinds of parameters: keys and file paths. A key would be "Eclipse-4.1" or "SonarCube-5.1". Files would be "file:...path..." I could then provide you with the keys as files (one line == one key) and you could add them to your framework.

Developers using this feature could use the provided lists or extract them from the sources or build their own.

**Comment by wmdietlGC** [comment]
Most keys can be found in `message.properties` files, e.g. `framework/src/org/checkerframework/common/basetype/messages.properties`.
In source code, uses of `checker/src/org/checkerframework/checker/compilermsgs/qual/CompilerMessageKey` can guide you find all keys.

As @mernst suggests, this is either a feature for Eclipse to integrate, or alternatively, you could write a simple stand-alone annotation processor that looks for `@SuppressWarnings`.
This is not a type system, is not specific to the Checker Framework, and would not benefit from any of the Checker Framework infrastructure as far as I can tell.
So I would suggest building this as a stand-alone project. We will be happy to link to this tool once it is finished. Thanks.
