### ISSUE TITLE
Better warning if a polymorphic qualifier is used on classes and fields

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#1376]
Currently polymorphic qualifiers are only supported in methods. It is a reasonable intuition that polymorphic qualifiers written on classes and fields will behave similarly to polymorphic qualifiers written on methods, but that isn't the case. The documentation on polymorphic qualifiers should explicitly call out that this feature is _not_ supported.

**Comment by kelloggm** [comment]
In addition, the framework itself should warn users who write polymorphic qualifiers on fields or classes that the feature is not supported, and should point back to this new documentation.

**Comment by mernst** [comment]
This is already documented.  Section 23.2 "Qualifier polymorphism" (https://checkerframework.org/manual/#qualifier-polymorphism) says, in its second paragraph:

> It may not be used on a class or field.

Methods can have type parameters but fields cannot.  Therefore, it's an incorrect intuition to think that the syntax and semantics should be the same for fields and methods.

Nonetheless, programmers might have this misconception.  Your suggestion is a good one:  issue a clear error message if a user writes polymorphic qualifiers on a field.  It would also be nice to support polymorphic qualifiers on classes.

**Comment by mernst** [comment]
Here are a few implementation suggestions if someone wants to address this.

Its related to issue #515.

However, the implementation would not use `@TargetLocations`, because we don't want to force every checker author who writes a checker to write.  Writing `@PolymorphicQualifier` should be enough.  To support this, the BaseTypeVisitor could have hard-coded logic to forbid annotations from being written in certain locations if the annotation is meta-annotated with `@Polymorphic`.

**Comment by wmdietl** [comment]
This should also check for uses of polymorphic qualifiers in extends clauses.
For example `class C extends List<@PolyTainted String>` should be forbidden?

Also usages in field initializers, instance initializers, and static instance initializers should be forbidden.
