### ISSUE TITLE
Dead link in annotate-jdk.sh

### ISSUE THREAD

**Issue by kelloggm** [typetools/checker-framework#1404]
The file `checker-framework/checker/jdk/annotate-jdk.sh` tries to download a file called `annotation-defs.jaif` from `https://checkerframework.org/annotation-defs.jaif`. That address gives a 404 if I try to access it, and my attempt to search the publicly-facing part of the site was unsuccessful (via google: "site:checkerframework.org annotation-defs.jaif". Is that file supposed to be publicly available and is currently missing? Has this script been deprecated and should it be removed from the repository? Is there a way to generate `annotation-defs.jaif` locally?

The command the script is executing when it fails is

```bash
# download annotation definitions
[ -r annotation-defs.jaif ]\
 || wget https://checkerframework.org/annotation-defs.jaif\
 || exit $?
```

My goal when I encountered this problem was to run the script to get a single set of annotated JDK source files from an unannotated JDK and a built Checker Framework distribution, which the script's documentation indicates is its purpose.

**Comment by mernst** [comment]
The script does not currently work.  The current attempt appears in the [branches](https://github.com/typetools/checker-framework/branches) annotated-jdk-2 and create-annotated-jdk-2.  If you want to help with that, you are welcome to.  Otherwise, we can try to increase the priority of that work if it is blocking you.

**Comment by kelloggm** [comment]
Thanks!
