### ISSUE TITLE
Can we have a checker-qual version with annotations only?

### ISSUE THREAD

**Issue by tmtron** [typetools/checker-framework#1510]
The `checker-qual.jar` file uses [annotations in comments][1], like this code from [NullnessUtil.java][2]:

```java
    public static @EnsuresNonNull("#1") <T extends /*@Nullable*/ Object> /*@NonNull*/ T castNonNull(
            T ref) {
        assert ref != null : "Misuse of castNonNull: called with a null argument";
        return (/*@NonNull*/ T) ref;
    }
```

The standard java 8 compiler just sees `/*@Nullable*/` as a comment. Thus, we must use the special `javac` compiler from the checker-framework.  
To setup the build chain to use it can be tricky (see e.g. the [gradle related issues][3]).

If we had a pure annotation version of the library, like this:

```java
    public static @EnsuresNonNull("#1") <T extends @Nullable Object> @NonNull T castNonNullA(T ref) {
        assert ref != null : "Misuse of castNonNull: called with a null argument";
        return (@NonNull T) ref;
    }
``` 
we would not need the special `javac`, right?

So would you consider to publish an annotation-only version of checker-qual in the future?

  [1]: https://checkerframework.org/manual/#backward-compatibility
  [2]: https://github.com/typetools/checker-framework/blob/549bf8f9621f19bd89876ecd7cf544851d064f74/checker/src/org/checkerframework/checker/nullness/NullnessUtil.java#L73
  [3]: https://github.com/typetools/checker-framework/issues?utf8=%E2%9C%93&q=is%3Aissue%20gradle

**Comment by wmdietl** [comment]
Annotations-in-comments are a source construct. The resulting `checker-qual.jar` is normal, valid Java bytecode.
To use the jar file, you don't need the special `javac`. You only need it to compile sources that contain annotations-in comments.

One special thing about `checker-qual.jar` is that it uses major version 51 bytecode (Java 7), but contains type annotations. We do this so that the same jar file can be used for Java 7 and Java 8 setups. Java 7 JVMs should ignore attributes they don't understand.

Can you explain what problem you're running into, so that we can see what should be changed? Are you having problems with the distributed `checker-qual.jar` file or do you try to build your own without using the special `javac`?

**Comment by tmtron** [comment]
In my project I use gradle, so it took me some time to build a minimal test to reproduce the issue without the build tool.

The following files need to be saved/executed in the `docs\example\` directory of the Checker-Framework 2.1.14:

## Annotations in comments don't work
```java
import org.checkerframework.checker.nullness.NullnessUtil;
import org.checkerframework.checker.nullness.qual.*;

public class NullnessUtilTest {

    public static boolean hasText(@Nullable String value) {
        return (value != null) && (value != "");
    }

    public static @NonNull String stringOrDefault(@Nullable String value, @NonNull String defaultValue) {
        if (hasText(value)) {
            return NullnessUtil.castNonNull(value);
        } 
        return defaultValue;
    }
}

```

When I run the `NullnessChecker`, like this:
```Batchfile
@echo off
set CF_DIST_DIR=..\..\checker\dist
echo on
javac ^
 -Xbootclasspath/p:%CF_DIST_DIR%\jdk8.jar ^
 -processorpath %CF_DIST_DIR%\checker.jar ^
 -processor org.checkerframework.checker.nullness.NullnessChecker ^
 -AsuppressWarnings=uninitialized ^
 -classpath %CF_DIST_DIR%\checker-qual.jar^
 -implicit:class ^
 NullnessUtilTest.java
```

it fails with this error
```Java
NullnessUtilTest.java:14: error: [return.type.incompatible] incompatible types in return.
                        return NullnessUtil.castNonNull(value);
                                                       ^
  found   : @Initialized @Nullable String
  required: @Initialized @NonNull String
1 error
```
## Annotated version works
But when I use an annotated version of the `NullnessUtil.castNonNull` function, it works.

To do this, I create a new file, which uses the real annotations instead of the comment-annotations:
```java
import org.checkerframework.checker.nullness.qual.*;

@SuppressWarnings({"nullness", "cast"})
public final class NullnessUtilTmt {

    public static @EnsuresNonNull("#1") <T extends @Nullable Object> @NonNull T castNonNullAnnotation(T ref) {
        assert ref != null : "Misuse of castNonNull: called with a null argument";
        return (@NonNull T) ref;
    }   
}
```
note, that the function is called `castNonNullAnnotation`, so we must change the test-file:
```java
...
if (hasText(value)) {
    return NullnessUtilTmt.castNonNullAnnotation(value);
} 
...
```
and add the new file to the source-files for the compilation:
```Batchfile
...
 -implicit:class ^
 NullnessUtilTest.java NullnessUtilTmt.java
```

now the compilation works fine.  

Thus, I suspected that an annotation-based `checker-qual.jar` file could solve this problem. But after your answer I am not sure anymore.

**Comment by wmdietl** [comment]
Thanks for producing these tests!

The problem is that only the jsr308-langtools javac reads type annotations out of v51 bytecode.
If you use the normal javac, which I assumed you are doing, the compiler will ignore the type annotations in `checker-qual.jar`.

The solution is that we need to split up `checker-qual.jar` into two versions, one for Java 7 and one for Java 8.
We do not need to duplicate the source code and remove the annotations-in-comments, we simply need to compile with corresponding `source/target` arguments.
