### ISSUE TITLE
Question regarding annotation runtime retention

### ISSUE THREAD

**Issue by kashike** [typetools/checker-framework#1615]
I've recently started depending on `org.checkerframework:checker-qual` for annotations such as `@NonNull` and `@Nullable`, and I noticed that these annotations (along with others) are [retained at `RUNTIME`](https://github.com/typetools/checker-framework/blob/master/checker/src/org/checkerframework/checker/nullness/qual/NonNull.java#L59) and I'm curious why this is necessary.

Thanks!

**Comment by wmdietl** [comment]
Welcome to the Checker Framework!
There is a discussion here: https://checkerframework.org/manual/#faq-runtime-retention
Please let us know if there is anything we should expand on.

**Comment by kashike** [comment]
That seems to have answered my question - I somehow missed that when searching earlier. :smile_cat:

**Comment by rbygrave** [comment]
> RUNTIME retention has negligible costs (no run-time dependency, minimal increase in heap size).

The checker-qual dependency is now ~220kb in size which for me personally I'd describe as non-trivial - for example that is 20% of the postgres jdbc driver. 

>  In other words, these type annotations are available to tools at run time.

To me this means that anything that depends and relies on these annotations **at runtime** effectively has this as a **part of their public API** - it somewhat indirectly becomes part of the API. Hmmm, I wonder if people are intentionally choosing this because to me that seems like a very big call - much bigger than the main job of _compile time checking_. Do people really want checker-qual to be part of their public API?

As I see it checker-qual as a dependency can be excluded at runtime - deemed a "provided" dependency / we can use maven exclusions to exclude it but then this can only be confirmed and runtime (and confirming nothing is actually dependent on the annotations at runtime) and this seems a bit yuk to me.

**Comment by mernst** [comment]
**Jar file size**

You make a good point that 220kb is not small.  That is `.jar` file size (most annotations will never be loaded from the `.jar` file), but `.jar` file size is still a cost.

The `checker-qual.jar` file contains 29 packages.  Four packages each account for around 10% of the size:
 * `org.checkerframework.checker.units`
 * `org.checkerframework.framework`
 * `org.checkerframework.checker.index`
 * `org.checkerframework.checker.signature`

All the other packages are 5% or less.  That is, the issue is that there are so many supported checkers, not that any one of the checkers has enormous annotations.


Here are some possible approaches, if jar file size is a deal-breaker:
 * Users can use `checker-qual-android` instead of `checker-qual`.  As [stated](https://checkerframework.org/manual/#android) in the manual: "The checker-qual-android artifact is identical to the checker-qual artifact, except that in checker-qual-android annotations have classfile retention."
 * Users can use a jar minimization tool, such as Maven's Shade, Gradle's Shadow, or a command-line tool like Jar Jar Links (it also works with Ant and Gradle).
 * The Checker Framework maintainers could create, in addition to the `checker-qual.jar` artifact, an artifact for each checker that contains only the annotations it needs, plus the annotations that those depend on, such as those in `org.checkerframework.framework`.  This entails creating and maintaining 20+ new Maven artifacts.

Maybe there are other approaches that I have overlooked.


**Run-time dependence on Checker Framework annotations**

You are right that, a run-time tool can depend on Checker Framework annotations, and thus on the checker-qual artifact.  (No part of the Checker Framework toolset does this, however, and I don't expect it is common today.)  A project should decide to use such a tool only if the benefits outweigh the costs (which you pointed out).

**Comment by rbygrave** [comment]
> Users can use checker-qual-android instead of checker-qual. As stated in the manual: "The checker-qual-android artifact is identical to the checker-qual artifact, except that in checker-qual-android annotations have classfile retention."

Apologies for missing that in the docs. To me this is the perfect solution for what I had in mind / what I was looking for so apologies for missing that and thanks!!

Hmmm, I should probably look to submit a doc PR for manual/#faq-runtime-retention in case other people also miss it.

**Comment by rbygrave** [comment]
Reference: FAQ doc PR to hopefully help - https://github.com/typetools/checker-framework/pull/4910

**Comment by mernst** [comment]
Thanks for the pull request.  That information was not easy to find before, so it's great to have the added cross-reference.

**Comment by vlsi** [comment]
@mernst , have you considered creating separate jars for separate annotation hierarchies?
For instance, create "per-package" modules: `checker-qual-nullable.jar`, `checker-qual-nullable.jar`, `checker-qual-units.jar`, and so on.
Then `checker-qual` could be a Maven `pom` artifact that depends on all the other `checker-qual-*.jar`

I believe that would address the issue of "200+KiB being too much" (by the way, I do not have 

A bit more fine-grained approach might work as well: for instance: `checker-qual-nullable-annotations` (module with annotations only), `checker-qual-nullable-spi` (the support classes like `NullnessUtil`)
