### ISSUE TITLE
CF vs JUnit

### ISSUE THREAD

**Issue by justmin** [typetools/checker-framework#1617]
I definitely do not understand how to use JUnit tests with CF

Simple test could not be compiled:

```


import org.checkerframework.checker.nullness.qual.Nullable;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

public class CFTest {
    private @Nullable String get(@Nullable String arg){
        return arg;
    }

    @Test
    public void test() throws Exception {
        assertNull(get(null));

        assertNotNull(get("not null"));

    }
}
```
Errors for both asserts:
 java: [argument.type.incompatible] incompatible types in argument.
  found   : @Initialized @Nullable String
  required: @Initialized @NonNull Object

**Comment by mernst** [comment]
The JUnit library is not yet annotated for nullness, so the Nullness Checker is treating it conservatively.
In other words, the Nullness Checker is assuming that unannotated methods must take a non-null argument.

Please see the section ["Checking partially-annotated programs: handling unannotated code"](https://checkerframework.org/manual/#unannotated-code) in the manual.  If you create an annotated version of the JUnit library, please share it so that we can include it in the Checker Framework distribution.

**Comment by spacether** [comment]
Related:
https://github.com/junit-team/junit5/issues/955
