### ISSUE TITLE
java.nio.FileSystemException in JDK is not modeled.

### ISSUE THREAD

**Issue by chengniansun** [typetools/checker-framework#1711]
I did not find the stub file for java.nio.FileSystemException. Has the java.nio package not been modeled yet?

**Comment by mernst** [comment]
Which type system are you trying to use?  So far, the `java.nio` package has only been modeled for the Index Checker, but not for other type systems.  This needs to be done.

If you wish to help out by contributing annotations, that would be great.  Otherwise, we will get to this as soon as we can.

Thanks for the bug report!

**Comment by chengniansun** [comment]
Thank you for your reply. I am using the nullness checker. I can contribute annotations if we decide to use the nullness checker widely.
