### ISSUE TITLE
Duplicate Nullness Initialization tests

### ISSUE THREAD

**Issue by wmdietl** [typetools/checker-framework#1776]
Both directories `checker/tests/nullness` and `checker/tests/nullness/init` contain the following files:

```
Uninit11.java
Uninit12.java
Uninit2.java
Uninit3.java
Uninit4.java
Uninit5.java
Uninit6.java
Uninit7.java
Uninit8.java
Uninit9.java
Uninit.java
```

Most of the files are identical, though some have differences. Also note that `init` contains a few extra `Uninit` tests.

As far as I can tell by looking at the `checker/tests/src/tests/NullnessXXXTest.java` files, the `init` directory uses the same configuration as `nullness`, so these tests are redundant.

Anyone know a reason why we should keep both?
I would be for removing the duplicates in `nullness` and keeping only the files in `nullness/init`.

**Comment by mernst** [comment]
I agree.

The tests were originally created in nullness/init

Stefan copied them to tests/nullness/nonnull2/* in commit f1d66d0b14b9ecd41997bdf51bd5cf2d727a652b.  Perhaps this was for testing the NullnessFBC type system separately from the NullnessRaw type system.

Stefan removed the tests/nullness/nonnull2/* directory in commit 
bb44b36ea8a664cb25de25a8af045aa35db022ed, but all its contents were placed in the top level rather than being put back into subdirectories.
