### ISSUE TITLE
Index Checker- IntelliJ: String.charAt is not checked

### ISSUE THREAD

**Issue by NhatDinh** [typetools/checker-framework#1906]
Consider:
```java
public class SimpleMethod1{
    static String simpleMethod(int i, String str) {
        int CONSTANT = 10;
        char[] array = new char[CONSTANT];

        array[i] = str.charAt(i);
        return str;
    }
    public static void main(String args[]) {
        simpleMethod(11, "whatever");
    }
}
```
Index Checker issued no warning at compile time, this will crash the program at run time.
I have also found more methods on string that also takes in an int as parameter.
If this is a valid concern, I would like to request a feature which checks on all these methods.

**Comment by NhatDinh** [comment]
Hi,
A quick update:I have recompiled the sample code block using command line and Index Checker issued warning str.charAt(i) as supposed too, however when compile using IntelliJ it does not. I have re-check the configuration steps with IntelliJ in the manual, everything is fine, it still issue other issues just not str.charAt(i). So I suspect its either because a bug in the manual or I'm terribly missing something.

**Comment by wmdietl** [comment]
Is the IntelliJ setup using the annotated JDK from `jdk8.jar`? That file needs to be on the bootclasspath to make the annotations visible to the processor.
Otherwise, the specification at https://github.com/typetools/checker-framework/blob/master/checker/jdk/index/src/java/lang/String.java#L660
isn't visible to the Index Checker.

**Comment by NhatDinh** [comment]
I got it working now. Thank you.

**Comment by NhatDinh** [comment]
The IntelliJ configuration section in the manual definitely need to be updated. The interface has changed and instruction such as" click on the green button" or find "-" is not accurate anymore. I would include my update suggestions in my proposal. 
Trouble shooting should be added as a sub set of IntelliJ( 31.6.1) and contains common errors such as the one I've got and stressing on how to resolve it.

**Comment by mernst** [comment]
Thanks for the suggestions.  I don't think this needs to be part of a GSoC proposal, because this should only take a small amount of effort (an hour or two, compared to a GSoC project which should represent 400 hours of work) and we should get it fixed before the summer.  Could you open a new issue for updating the IntelliJ instructions, and hopefully even provide a proposed fix?  Thanks!

**Comment by NhatDinh** [comment]
Yes, I will write up my suggestions, proposed update and open a new issue to fix it.
Thanks!
