### ISSUE TITLE
Faulty implemetation of InternalForm annotation

### ISSUE THREAD

**Issue by gsaga** [typetools/checker-framework#2008]
The current implementation of signature checker will recognize `java/lang/Object[]` as the internal form of the signature of an array of `Object`s when it should be `[Ljava/lang/Object;`.

The internal form signature *is* exactly equal to the output of Class.getName with '.'s replaced with '/'s. The  JVM specs say that the Internal Form of a signature of a type is equal to the **binary name** with '.'s replaced with '/'s" (https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-4.html#jvms-4.2.1). But that's only true for binary names of non array types. As Remi Forax from ASM mailing list [states](http://asm.objectweb.narkive.com/SEQPgPWW/what-s-the-precise-definition-of-an-internal-name):

    because historically, prior to 1.5 i think, you were not able to use an array as an internal name

This is backed by the following sections of jvm specs:

https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-4.html#jvms-4.3.2 (near the end of section 4.3.2)

https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-4.html#jvms-4.3.3 ( In the second box)

I'm working on fixing this in the following branch: https://github.com/gsaga/checker-framework/tree/fixInternalName

**Comment by mernst** [comment]
Thanks for the details.  I'm asking the JVMS authors for clarification of the inconsistency between section 4.2 and section 4.3.

In the meanwhile, I will remark that Remi Forax's [message](http://narkive.com/SEQPgPWW:2.621.144) is a bit confusing.

He says
"I've always though that the section 4.1 was confusing",
but section 4.2 (not 4.1) defines internal form.

He also says,
"The section 5.1 is more precise of what is an internal name of an array https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-5.html#jvms-5.1".
but neither the term "internal form" or "internal name" appears anywhere in JVMS chapter 5, much less in section 5.1 which is about the constant pool representation, not the internal form.

**Comment by mernst** [comment]
Internal form does not have a representation for arrays, because it is a variant of binary names.
Binary names do not have a representation for arrays, because binary names are used for class loading, and arrays and primitives are irrelevant to class loading.  I have opened #2098 to correct this.

You mentioned references in the JVM spec:
https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-4.html#jvms-4.3.2 (near the end of section 4.3.2)
https://docs.oracle.com/javase/specs/jvms/se10/html/jvms-4.html#jvms-4.3.3 ( In the second box)

The wording is ambiguous, and unfortunately your interpretation is not the one intended by the JVMS authors.  The text in section 4.3.2 is "The field descriptor of an instance variable of type Object is Ljava/lang/Object;. Note that the internal form of the binary name for class Object is used."  Alex Buckley clarifies this:

> It says that the field descriptor `Ljava/lang/Object;` "uses" the internal form of the binary name for Object. That is, the field descriptor "uses" `java/lang/Object` among other things, such as how it "uses" the `L` prefix to denote a reference type.

I think it would be clearer to change the text in JVMS 4.2.1 from

> Note that the internal form of the binary name for class Object is used.

to

> Note that the field descriptor embeds the internal form of the binary 
name for class Object, "java/lang/Object".

because that's what the text is trying to say.
