### ISSUE TITLE
OSGI support in MANIFEST.MF

### ISSUE THREAD

**Issue by markwoon** [typetools/checker-framework#2065]
Please add OSGI bundle information to checker-qual's `MANIFEST.MF`.

It should be as simple as adding the osgi plugin in `build.gradle`.

**Comment by mernst** [comment]
It's not that simple; just making this change:
https://github.com/mernst/checker-framework/commit/1078ad38059376927d9de7377cbcca4e5bd475f2
leads to build failures; see https://travis-ci.org/mernst/checker-framework/builds/401226220 .
If you could submit a pull request, that would be great, since I am not familiar with OSGI.

**Comment by mernst** [comment]
I'm closing this issue because the original poster has not responded.
We would still welcome a pull request that addresses the issue, if it is affecting anyone else.
