### ISSUE TITLE
Convert JDK Annotations to Eclipse format, to enable use of Eclipse IDE notifications

### ISSUE THREAD

**Issue by bmhm** [typetools/checker-framework#2157]
Hello,

I just found out that eclispe photon does now provide a way to add annotations to existing libraries. This is also true for JDK libraries.

If you go to Eclipse -> Preferences -> Installed JDKs -> Edit 
then open a tree from let's say  `rt.jar`, there is now an option to attach an annotation file.

I found two resources:
https://wiki.eclipse.org/JDT_Core/Null_Analysis/External_Annotations (specific to the option)
and
https://wiki.eclipse.org/JDT_Core/Null_Analysis (more generic)

The first page links an annotation file format page:
https://checkerframework.org/annotation-file-utilities/annotation-file-format.html

So my question is: How can checker support this, so we can use Eclipse's built in feature?

Thanks a lot!

**Comment by mernst** [comment]
Can you clarify your question?
Do you want to convert Eclipse annotations into the Annotation File Format?
Do you want to convert `.jaif` annotation files into Eclipse's format?
Do you want to extend the Checker Framework to support a new new annotationpath attribute and read Eclipse's file format?
Or maybe something else?

As background, Eclipse defined its own file format
(https://wiki.eclipse.org/JDT_Core/Null_Analysis/External_Annotations#File_format) rather than adopting the Annotation File Format.
Eclipse's file format works only for nullness annotations.  It is more compact but less readable than the Annotation File Format.  It is intended for tool use, not for editing by ordinary users, who are expected to interact with it via the Eclipse GUI.

**Comment by bmhm** [comment]
Hey, thanks for your quick answer and sorry for not clarifying enough.

I'd like to attach an eclipse file in their own format, containing the checker.qual.Nullable annotations. This way I could see null problems in eclipse.

The idea is that the plugin is marked deprecated by your documentation, and I am looking for another way to see null problems in the code.

This would also mean that checker needed a NotNullByDefault annotation (just for eclipse), I saw another bug about this already.

I think the eclipse file could and should be generated from your jdk8.jar.

I cannot just add it on top of the existing rt.jar. tried it, but getting odd errors for map types and Streams with collectors resulting in a list, because it's impossible to figure out if there might be a Nullable object which will get collected.

So I thought their annotation format might suit this need best.

**Comment by mernst** [comment]
Thanks for the clarification.  That is very helpful context.
Your goal is to get immediate IDE warnings in Eclipse as you type.  Currently, you need to run your build to see the Checker Framework's warnings.

Note that the Eclipse nullness analysis is significantly different than the Nullness Checker of the Checker Framework.  Eclipse issues more false positives, and Eclipse suffers false negatives.  Therefore, it is a distraction to be notified about some of Eclipse's warnings (the false positives), and even after you have edited your code to make Eclipse issue no more warnings, your real build may issue more warnings.  Trying to satisfy two different tools sounds like a lot of work and not a good use of your time.

You bring up a good point, though:  The Eclipse analysis's IDE integration is much better than the Checker Framework's Eclipse integration, and it would be better for Eclipse users to get Checker Framework warnings via he incremental project builder (if not the model reconciler).  The deprecated Checker Framework Eclipse plugin was built a long time ago, and the Eclipse plugin API has improved since then.  It should be possible to create a new Eclipse plugin, possibly adapting some existing Eclipse plugin.  We don't have the manpower to do that right now, but would welcome an external contribution.

**Comment by bmhm** [comment]
Hello @mernst I can really see what makes it difficult. 

Perhaps it might be an idea to create a new plugin. The new plugin could (or even should) disable the integrated checks in eclipse for configureg projects and get the errors from gradle and/or maven. Might be the best solution. I don't think we need a `@<sth>NonNullByDefault` annotation, which eclipse wants. `null` should be treated as special case as it is right now.

I don't think I can create a eclipse plugin, and as their artefacts are not on maven, I always find it a hazzle to create a plugin.

**Comment by mernst** [comment]
Thanks.  I'll close this issue for now.  If someone who is familiar with Eclipse plugin development could create a plugin, we would appreciate it.
