### ISSUE TITLE
Don't allow Optional.fromNullable on something that's not @Nullable

### ISSUE THREAD

**Issue by b0ri5** [typetools/checker-framework#2158]
Could the checker framework find cases like

String s = "something";
Optional.fromNullable(s).orElse("something-else");

and then notice that s is not nullable and so Optional.fromNullable(s).orElse("something-else") could be replaced with "something-else"?

A similar request would be to let users know if they use Guava's Preconditions.checkNotNull on a non-nullable value.

**Comment by wmdietl** [comment]
The Nullness Checker has special `-Alint=redundantNullComparison` option to ensure that a non-null variable isn't compared against null.
Something similar should be doable for `fromNullable`.

In your example, wouldn't the result always be `something`, because `s` is non-null?

Regarding Guava, note that `Preconditions.checkNotNull` https://github.com/typetools/guava/blob/master/guava/src/com/google/common/base/Preconditions.java#L906
only allows non-null arguments.
The type system aims to statically prevent these exceptions, so only non-null values are allowed.

**Comment by mernst** [comment]
To make `-Alint=redundantNullComparison` issue a warning when `fromNullable`'s argument has type `@NonNull` would probably require a new annotation that can be placed on the formal parameter (type?) of `fromNullable`.  The new annotation would indicate that this formal parameter is unlike most:  for most formal parameters annotated as `@Nullable`, it's OK to use a `@NonNull` argument.  This seems like too much mechanism for a minor issue; @b0ri5, is the problem serious for you?

**Comment by b0ri5** [comment]
@wmdietl Thanks for the pointer to -Alint=redundantNullComparison - I don't think it's enabled for us and will look into it. Yes, it should be "something" sorry for the confusion. It also looks like our Guava library doesn't yet use the commit that adds @NonNull to checkNotNull. I'll follow up on that too (but not too soon).

@mernst No the problem is not serious, but code like this can definitely be confusing so if there's a way to ensure it's removed and doesn't get added that would be nice.

**Comment by mernst** [comment]
Thanks for the followup.  I'll close this for now.  If you or someone else wishes to contribute the feature, we would welcome a patch.

**Comment by b0ri5** [comment]
Okay thanks.
