### ISSUE TITLE
NullPointerException in BaseTypeChecker.typeProcess

### ISSUE THREAD

**Issue by pszyszuk** [typetools/checker-framework#3093]
At execution of "mvn clean package -X" command I got the following exception:
Caused by: java.lang.NullPointerException
    at org.checkerframework.common.basetype.BaseTypeChecker.typeProcess (BaseTypeChecker.java:478)
    at org.checkerframework.javacutil.AbstractTypeProcessor$AttributionTaskListener.finished (AbstractTypeProcessor.java:182)
    at com.sun.tools.javac.api.ClientCodeWrapper$WrappedTaskListener.finished (ClientCodeWrapper.java:681)
    at com.sun.tools.javac.api.MultiTaskListener.finished (MultiTaskListener.java:111)
    at com.sun.tools.javac.main.JavaCompiler.flow (JavaCompiler.java:1342)

Full call stack attached in file NullPointerException-BaseTypeChecker.typeProcess.txt

maven version 3.6.2
org.checkerframework version 3.1.1
Java version 1.8.0_201

pom.xml settings applied according to https://github.com/typetools/checker-framework/blob/master/docs/examples/MavenExample/pom.xml

What other details are needed to investigate the problem?

Call stack:
[NullPointerException-BaseTypeChecker.typeProcess.txt](https://github.com/typetools/checker-framework/files/4214270/NullPointerException-BaseTypeChecker.typeProcess.txt)

**Comment by mernst** [comment]
I'm sorry you are having trouble.  We would like to help you, but we cannot do so from this incomplete bug report.  Can you please provide all the details that were requested in the issue template?  In particular, we need the exact command you ran, a transcript of all the output (not just part of it), and the files that you ran your command on.  This will enable us to reproduce and fix your problem.  Thanks!

**Comment by pszyszuk** [comment]
Attached log with obfuscated names which might disclose the priprietary information:
[_20200217_compile_errors.DEBUG.external-visibility.txt](https://github.com/typetools/checker-framework/files/4214446/_20200217_compile_errors.DEBUG.external-visibility.txt)

**Comment by pszyszuk** [comment]
Changes to existing project were done only in the pom.xml file, diff atached:
[diff-pom.xml.txt](https://github.com/typetools/checker-framework/files/4214483/diff-pom.xml.txt)

No annotations were added to the code yet.

If the attached information is not sufficient to analyse the problem further, could you suggest some troubleshooting steps?

**Comment by mernst** [comment]
Ah, thanks for clarifying that you are using proprietary source code that you cannot share.

The problem seems to be that `BaseTypeChecker.typeProcess` was called before `BaseTypeChecker.initChecker`.  (`initChecker` set `messageStore` to non-null.)   We could add a guard against `messageStore == null` in `BaseTypeChecker.typeProcess' to prevent the NullPointerException, but that would just mask the problem and I am concerned that it would arise in some even harder-to-diagnose situation.

I don't recall a failure like this before.  Your log shows that you are using Lombok and possibly other annotation processors.  I wonder whether some interaction with them is responsible for the problem.  We have seen such problems before.  For example, Lombok does sneaky things in the compiler that prevent other annotation processors from running or seeing full code.

It would be really helpful if you could minimize the problem to type-checking of a small piece of code that you can scrub of trade secrets and share.

You can help localize the file that was being type-checked by using the [progress tracing](https://checkerframework.org/manual/#creating-debugging-options-progress) options.  Then, you could see whether the problem happens when you run type-checking on fewer files.  You could also determine whether the problem happens when you do not use Lombok.  This could help you find a small test case that you could share with us.

Let us know if there are things we can do to help from our end.

**Comment by pszyszuk** [comment]
I was able to reproduce the problem on a project I can share:
[NulPointerException-BaseTypeChecker.tar.gz](https://github.com/typetools/checker-framework/files/4219551/NulPointerException-BaseTypeChecker.tar.gz)

Maven log:
[mvn-3.6.2.log.txt](https://github.com/typetools/checker-framework/files/4219552/mvn-3.6.2.log.txt)

**Comment by mernst** [comment]
Thanks for minimizing!  I appreciate it.
The simplicity of the test case makes it clear there is some problem with the Maven buildfile.

I wasn't able to reproduce your problem, unfortunately.  Running `mvn clean package -X` (in either the top-level directory or the `module1` subdirectory) yields:
```[FATAL] Non-resolvable parent POM for com.tibco:module1:[unknown-version]: Failure to find com.tibco:tibjms:pom:4.4.3 in https://repo.maven.apache.org/maven2```
Here is the complete log of commands that I ran:
[issue3093-repro.txt](https://github.com/typetools/checker-framework/files/4220688/issue3093-repro.txt)
Could you adjust your example so that I can run it?
Thanks again.

**Comment by pszyszuk** [comment]
Simplified project to demonstrate NullPointerException in Checker framework uploaded to github:
https://github.com/pszyszuk/cf_npe

Maven log attached
[mvn.log.txt](https://github.com/typetools/checker-framework/files/4224165/mvn.log.txt)

Problem reproducible with other versions of mvn (e.g. IntelliJ bundled Maven 3.3.9). I used mvnvm (Maven Version Manager mvnvm.org)

**Comment by smillst** [comment]
Thanks for the simple project!  I can reproduce this now.

**Comment by smillst** [comment]
`module1/pom.xml` is missing `<fork>true</fork>` in the maven-compiler-plugin block:
```
  <plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.0</version>
    <configuration>
      <fork>true</fork>
```
Also it needs the maven-dependency-plugin:
```
      <plugin>
          <!-- This plugin will set properties values using dependency information -->
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <executions>
              <execution>
                  <goals>
                      <goal>properties</goal>
                  </goals>
              </execution>
          </executions>
      </plugin>
```

If I add both of these, the NPE goes away.

**Comment by pszyszuk** [comment]
Thanks! This solves the problem.

**Comment by wmdietl** [comment]
@smillst If the fork=true or maven-dependency-plugin are missing, are we guaranteed to run into this NPE? Or are there many other ways in which these configuration problems can manifest themselves?
If this NPE is most likely caused by this incorrect Maven configuration, it might be worth it to check for it and output a more helpful error message.

**Comment by smillst** [comment]
@wmdietl I don't understand why this misconfiguration caused the NPE.  `typeProcess` was called before `initCheckers()` completed, so I don't think it makes sense to output a more helpful error message.
