### ISSUE TITLE
The :checker:cloneTypetoolsJdk task should refer to a specific version

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#3263]
The [`:checker:cloneTypetoolsJdk` task](https://github.com/typetools/checker-framework/blob/master/checker/build.gradle#L39-L58) either clones the master branch of https://github.com/typetools/jdk or does a `git pull` to get the latest version.  This makes builds non-reproducible; an old Checker Framework git version may no longer build properly (or tests may fail) due to updates in the `typetools/jdk` repository.  It would be better if this task always checked out a specific git SHA from `typetools/jdk`, with the SHA specified in the Checker Framework build files.  In addition to making builds more reproducible, this change would make builds faster, as no `git` command would need to be run when the appropriate git SHA was already checked out.

On the downside, pulling in new changes from `typetools/jdk` would require manually updating a SHA in a Checker Framework build file.  But to me this seems worthwhile.

**Comment by wmdietl** [comment]
Whe use a sha-hash to check out a specific `jdk8.jar` file: https://github.com/typetools/checker-framework/blob/master/checker/build.gradle#L5
I agree that we should do the same for `typetools/jdk`.

**Comment by mernst** [comment]
The disadvantage of the current scheme is that when a user is both making changes to the JDK and making changes to the `checker-framework` repository (in branches of the same name), both of those branches need to be checked out.  Failure to do so will lead to using the wrong JDK.  (You also note that running a git command has a performance penalty.  A user could provide the gradle `-x` or `--exclude-task` flag to avoid that problem.)  Are there other disadvantages?

A disadvantage of the proposed scheme is that making a change just to JDK annotations requires edits in two repositories instead of just in the `jdk` repository, and two pull requests instead of one.  This is a hassle for users, and I would like to reduce the bar to contributing to the JDK.  Users may forget the extra step.  The SHA hashes will always conflict even if the changes in the JDK annotations do not conflict, leading to extra work.  Another small disadvantage is that giving a specific SHA hash would also make it impossible to just rerun just part of the  CI tests after making a tweak to the `jdk` repository -- it will now be necessary to make a commit to the `checker-framework` repository and start a new CI run.  (Though maybe you see that as a positive.)

As background, this isn't a problem for continuous integration.  The CI jobs use [`git-clone-related`](https://github.com/plume-lib/plume-scripts/blob/master/git-clone-related) to clone the appropriate branch.  They are careful to do this *before* the `:cloneTypetoolsJdk` task has a chance to run because the `:cloneTypetoolsJdk` task lacks this logic.  Would you prefer to build the logic into the `:cloneTypetoolsJdk` task, or call `git-clone-related` from it?  I think that would make sense, though it does adding complexity to that task.

**Comment by msridhar** [comment]
First, this is not a high-priority issue for me.  I just noticed it and wanted to open an issue before forgetting.

Possibly naive question.  Is it important to keep `jdk` as a separate repository?  I could see why it might be, e.g., to pull in upstream `jdk` changes or due to licensing issues.  The "monorepo" philosophy would say the solution to this problem is to combine the relevant code from the repositories into one, but I can understand if that's not feasible.

With a bit of coding and use of the GitHub APIs, it may be possible to build a bot that automatically opens a PR on this repository when a new commit lands on the `master` branch of the `jdk` repository.  That could help address the two pull request problem, but it will take some work.

> As background, this isn't a problem for continuous integration. The CI jobs use git-clone-related to clone the appropriate branch. They are careful to do this before the :cloneTypetoolsJdk task has a chance to run because the :cloneTypetoolsJdk task lacks this logic. Would you prefer to build the logic into the :cloneTypetoolsJdk task, or call git-clone-related from it? I think that would make sense, though it does adding complexity to that task.

I'm not sure I follow this.  Isn't this only relevant when you have simultaneous changes in both repositories that you need to test together?  I don't think it solves the problem of checking out and building an old version of the master branch of the Checker Framework, since the information regarding what is the corresponding version of `jdk` is not recorded AFAIK.

**Comment by mernst** [comment]
Thanks for raising the issue.  It's definitely worth discussing.

I would like to keep `jdk` as a separate repository, because of the way we pull changes from upstream.  (Also because of licensing.  Also because it is massive; we could solve that by giving up on maintaining history, but that would lead to other problems.)  I agree that monorepos solve a lot of problems!  For example, we are considering merging the `checker-framework` and `annotation-tools` repositories.

> With a bit of coding and use of the GitHub APIs, it may be possible to build a bot that automatically opens a PR on this repository when a new commit lands on the master branch of the jdk repository. That could help address the two pull request problem, but it will take some work.

Yes, this would be possible.  Users would still have to make multiple related pull requests in other situations, when a change to the Checker Framework necessitates annotation changes in annotated programs that we use as test cases.  These are the CI tests named "daikon", "guava", "plume-lib", and "downstream".

> Isn't this only relevant when you have simultaneous changes in both repositories that you need to test together?

Yes, that is right.  Sorry that wasn't clear.

> I don't think it solves the problem of checking out and building an old version of the master branch of the Checker Framework, since the information regarding what is the corresponding version of jdk is not recorded AFAIK.

You are right.  But I don't recall ever doing that -- I usually try to fix the problem at HEAD and encourage users to upgrade, or users can use an older release if we have a regression.  If we had paying customers, the answer to this might be different.

**Comment by msridhar** [comment]
> I would like to keep `jdk` as a separate repository, because of the way we pull changes from upstream. (Also because of licensing. Also because it is massive; we could solve that by giving up on maintaining history, but that would lead to other problems.) I agree that monorepos solve a lot of problems! For example, we are considering merging the `checker-framework` and `annotation-tools` repositories.

Sure, that makes sense.

> > I don't think it solves the problem of checking out and building an old version of the master branch of the Checker Framework, since the information regarding what is the corresponding version of jdk is not recorded AFAIK.
> 
> You are right. But I don't recall ever doing that -- I usually try to fix the problem at HEAD and encourage users to upgrade, or users can use an older release if we have a regression. If we had paying customers, the answer to this might be different.

Usually it's not about patching an old version, but searching for which change caused a regression (one not covered by existing tests), e.g., by using `git bisect`.  This kind of search becomes really difficult when you can't rely on being able to build and test every commit on the branch.  But it's possible that for the Checker Framework, this is not a big problem in practice.

**Comment by mernst** [comment]
Ah, I see your point now.  I do bisect sometimes.  But I find that the two repositories can be bisected independently in order to run a test case (even if one would need to use timestamps to run every test).

**Comment by msridhar** [comment]
Yes, bisecting the repositories simultaneously will work I think.  It's a bit of extra work but could be automated with scripting.

I think the discussion here outlines the tradeoffs pretty well.  As I mentioned before, there is no urgency for me personally regarding this issue.

**Comment by wmdietl** [comment]
We discussed this issue a bit today. The jdk dependency will use `plume-scripts/git-clone-related` to pull in a related branch and the jdk repo will get CI testing.

**Comment by mernst** [comment]
Testing added in https://github.com/typetools/jdk/commit/f8b2cd0c9acdffc0ca0d4ea5ba19422131946b0c
