### ISSUE TITLE
-version produces "javac (version info not available)"

### ISSUE THREAD

**Issue by cpovirk** [typetools/checker-framework#3381]
Since the default issue template suggests including the output of `-version`, I've noticed that, for a while now, the output of that has been:

`javac (version info not available)`

If I go all the way back to Checker Framework 2.10.0, I see:

`javac 1.8.0-jsr308-2.4.0`

But every version I had handy for testing from 2.11.0 onward has "version info not available."

(I wonder if ideally the version output would include the version of the Checker Framework itself?)

**Comment by wmdietl** [comment]
I had recently noticed something similarly.
Up to 2.11.0 we used our own jsr308-langtools compiler, in which we had added the Checker Framework version numbers.
We now use either the error-prone javac (if run on a Java 8 JVM) or the host javac (for a Java >=9 JVM).

For example, I get:

```
./checker/bin/javac -version
javac 11.0.7
```

because that's the host compiler version I seem to be using.

I don't think we can easily intercept how javac outputs the version number.
How about adding an `-Aversion` flag that we can use to output the Checker Framework version?

**Comment by wmdietl** [comment]
Implementation tasks:
- add a new key `"version"` to the set of supported options: https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java#L373
- in `typeProcessingStart` check for the new option: https://github.com/typetools/checker-framework/blob/master/framework/src/main/java/org/checkerframework/framework/source/SourceChecker.java#L762
- use messager to output the version
- make sure the version string gets updated automatically, using `checker-framework-version` and `checker-framework-date` magic https://github.com/typetools/checker-framework/blob/master/docs/developer/release/release.properties
