### ISSUE TITLE
Feature request: forward and backward compatibility modes

### ISSUE THREAD

**Issue by vlsi** [typetools/checker-framework#3650]
Different projects might adopt different checker-framework versions, however, it might result in incompatible dependency versions.

Sample: https://github.com/pgjdbc/pgjdbc/issues/1887

`com.google.guava:guava:guava:jar:27.1.0-jre => org.checkerframework:checker-qual:checker-qual:jar:2.5.2`
`org.postgresql:postgresql:42.2.15 => org.checkerframework:checker-qual:checker-qual:jar:3.5.0`

It might be extremely challenging to make all the projects to use the same `checker-qual` version, so there should be a way to apply checker-framework in such a way, so the resulting libraries are compatible.

I could see the following:
a) Avoid dropping the old annotations. This is basically the same as "avoid altering the major version"
b) Use different artifact ID for different major versions. For instance: `:checker-qual3:3.5.0` vs `:checker-qual2:2.5.2`, then both artifacts could be used at the same time. Apparently that would need to use different package names.
c) Something other?

WDYT?

**Comment by mernst** [comment]
You are right that this is a problem.  Thanks for bringing it up.

I think this is a general dependency management problem.  Is that assesment correct, or is there something specific to the Checker Framework?

> a) Avoid dropping the old annotations. This is basically the same as "avoid altering the major version"

I agree with this proposal.  It's our general policy.  We are not perfect: there were 9 type qualifiers renamed, and their old versions removed, between 3.0.0 and 3.6.1.  We alwayss bumped the minor version (middle version number) when doing this.  (For the record, they are `@BinaryNameInUnnamedPackage` `@FieldDescriptorForPrimitiveOrArrayInUnnamedPackage` `@IdentifierOrArray` `@DefaultInUncheckedCodeFor` `@DefaultQualifierInHierarchyInUncheckedCode` `@DefaultQualifiers` `@EnsuresQualifiers` `@EnsuresQualifiersIf` `@RequiresQualifiers`.)  Are there specific ones of these (or others that were removed earlier) that are giving trouble?  If you can point them out, we can devise a solution for those particular annotations.

> b) Use different artifact ID for different major versions. For instance: :checker-qual3:3.5.0 vs :checker-qual2:2.5.2, then both artifacts could be used at the same time. Apparently that would need to use different package names.

There could still be a problem with conflicting imports of different versions of `checker-qual3` in that case, correct?  So this seems to be a partial rather than a complete solution, unless I am missing something.  (Also, I am reluctant to change package names, which would be a big barrier to users upgrading.)


Another solution would be to encourage clients of the Checker Framework to upgrade to a newer version.  Checker Framework version 2.5.2 is more than 2 years old -- there have been 28 releases since then.  We could periodically submit pull requests to key projects like Guava to use a newer version of the dependency.  This would help avoid large version skews, but would not itself solve the problem.

Yet another solution would be to decouple the version numbers of the checker-qual and checker artifacts, because checker-qual changes less frequently than checker does.  Then there would be fewer versions of checker-qual floating around, but sometimes the version of `checker-qual` would differ from that of `checker`, which I think would be confusing to users.

Regarding https://github.com/pgjdbc/pgjdbc/issues/1887, I suggest the proposed workaround 2:

> Force a skip on this compatibility check and assume runtime API compatibility for Google Guice / Guava with version 3.5.0.

**Comment by vlsi** [comment]
> There could still be a problem with conflicting imports of different versions of checker-qual3 in that case, correct? 

I assume that `checker-qual3` annotations would use class names like `org.checkerframework.framework.qual3.DefaultQualifier`.

Then there's no issue with using `checker-qual3` and `checker-qual2` in the same application.

>We could periodically submit pull requests to key projects like Guava to use a newer version of the dependency.

I'm afraid we can't make everybody to use the newer versions since they might have old Guava versions deployed in production.

**Comment by vlsi** [comment]
>I think this is a general dependency management problem. Is that assesment correct, or is there something specific to the Checker Framework?

Even though it might look like a general problem, CheckerFramework case is slightly different.
`checker-qual` dependency contains almost no code, and the key point of listing `checker-qual` dependency is to make annotations resolvable (e.g. when reflection is used) and help compilers to process classes (certain compilers fail to parse bytecode if annotations are not on the classpath).

It is not like `checker-qual` is used to implement a feature in the runtime, but it is more like an extra metadata.

**Comment by vlsi** [comment]
>  Are there specific ones of these (or others that were removed earlier) that are giving trouble?

I've no idea, however, I see Guava uses `NullableDecl` a lot, and I assume it is not present in the current checkerframework versions: https://github.com/google/guava/search?q=NullableDecl&unscoped_q=NullableDecl , https://github.com/google/truth/issues/497

**Comment by mernst** [comment]
> > There could still be a problem with conflicting imports of different versions of checker-qual3 in that case, correct?
> 
> I assume that `checker-qual3` annotations would use class names like `org.checkerframework.framework.qual3.DefaultQualifier`.
> 
> Then there's no issue with using `checker-qual3` and `checker-qual2` in the same application.

I meant that there could still be a problem if one package uses version 3.1.0 and another package uses version 3.2.0.  (Sorry for my message being unclear.)

> > We could periodically submit pull requests to key projects like Guava to use a newer version of the dependency.
> 
> I'm afraid we can't make everybody to use the newer versions since they might have old Guava versions deployed in production.

I agree.  (I noted that these updates are a useful thing to do to avoid large version skew, but they are not a solution.)

> It is not like `checker-qual` is used to implement a feature in the runtime, but it is more like an extra metadata.

The `checker-qual` package does contain code that a program can call at run time.  This code is contained in the following classes: `FormatUtil` `I18nFormatUtil` `NullnessUtil` `Opt` `RegexUtil` `SignednessUtil` `SignednessUtilExtra` `UnitsTools` `PurityUnqualified`.  I agree that `checker-qual` is more commonly used for its annotations than for its code.

> I see Guava uses `NullableDecl` a lot, and I assume it is not present in the current checkerframework versions: https://github.com/google/guava/search?q=NullableDecl&unscoped_q=NullableDecl , [google/truth#497](https://github.com/google/truth/issues/497)

Guava gets that annotation from the `checker-compat-qual` artifact, not from the `checker-qual` artifact.  So I don't think that annotation is a problem.

I suspect that for almost all uses, the `checker-qual` artifacts are **backward compatible**.

I don't see how to achieve **forward compatibility** (without re-releasing old artifacts, which could have its own problems):  code that depends on an annotation that was introduced in version 3.8.1 will not find that annotation if version 3.0.0 is supplied to it.

**Comment by vlsi** [comment]
> if one package uses version 3.1.0 and another package uses version 3.2.0

I do not mean `semver` is the only way to go, however, the general expectation is if one package is using 3.1.0, and another uses 3.2.0, then 3.2.0 should be ok for both of them. In other words, class/method removals are not allowed between 3.1.0...3.2.0 from semver point of view.

For instance, if 3.2.0 adds a new annotation, then it would be ok for both libraries.

>  This code is contained in the following classes

It might make sense to separate annotations and code to different packages.

>I don't see how to achieve forward compatibility

By forward compatibility I mean designing `checker-qual` in such a way so it does not break if another library in the same application chooses to use a newer `checker-qual` version.

**Comment by mernst** [comment]
> It might make sense to separate annotations and code to different packages.

Sure, that is a good suggestion.

> By forward compatibility I mean designing `checker-qual` in such a way so it does not break if another library in the same application chooses to use a newer `checker-qual` version.

Thanks for clarifying.  I think that your are describing [backward compatibility](https://en.wikipedia.org/wiki/Backward_compatibility):  a system designed to use an older version of `checker-qual` still works with a newer version of `checker-qual`.  And I think that `checker-qual` (nearly) achieves that.  Please let us know if you find places where it does not.

**Comment by mernst** [comment]
@vlsi Can we close this issue?
