### ISSUE TITLE
Non-free file in repository (NotNull.java)

### ISSUE THREAD

**Issue by olekw** [typetools/checker-framework#3819]
While the overall checker/src/testannotations/ directory is listed as licensed under an MIT-style license, a member of the Debian FTP Team noted that the NotNull.java file located at checker/src/testannotations/java/javax/validation/constraints/NotNull.java is actually under a non-free license. This can be verified by referencing the [upstream link in the file](https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/NotNull.html) and then reading the [license terms](https://javaee.github.io/javaee-spec/javadocs/doc-files/speclicense.html) section at the bottom. 

Please remove this file and replace with an Open Source equivalent. Given Oracle's problematic licensing, it may be worth replacing any other javax code as well. Thank you!

**Comment by olekw** [comment]
@mernst the latest Debian review identified a number of files where the licensing does not match the LICENSE.txt file. Those are all administrative changes (and I'll forward those in a separate issue) except for this one. In the interests of getting checker-framework into Debian reasonably quickly, do you have a suggestion for a quick way to address this issue? Thanks.

**Comment by mernst** [comment]
Thanks for pointing this out.  I appreciate it.

I will make a pull request that:
 * clarifies that all annotations with an upstream version are clean-room reimplementations thereof
 * removes the JavaEE annotation because Oracle doesn't believe in clean-room reimplementations

The other javax annotations aren't from Oracle; they are from FindBugs or JSR 305, which (against the rules) put its annotations in javax.  So I think they are OK.

Does this sound adequate?

**Comment by olekw** [comment]
Sounds reasonable to me, thanks! If the license experts at Debian have additional concerns I'll update this issue.

**Comment by olekw** [comment]
And thanks for the quick resolution, as always! :)
