### ISSUE TITLE
Heap overflow

### ISSUE THREAD

**Issue by baloghadamsoftware** [typetools/checker-framework#4206]
Hello,

I was testing various Java analyzer tools on different projects used as test projects. One analyzer tool was the test project of another one :-) Last time Spotbugs was the test project for the Checker Framework.

I used the following config (in the build.gradle file):
```
  checkerFramework {
      checkers = [
      'org.checkerframework.checker.calledmethods.CalledMethodsChecker',
      'org.checkerframework.checker.compilermsgs.CompilerMessagesChecker',
      'org.checkerframework.checker.fenum.FenumChecker',
      'org.checkerframework.checker.formatter.FormatterChecker',
      'org.checkerframework.checker.index.IndexChecker',
      'org.checkerframework.checker.interning.InterningChecker',
      'org.checkerframework.checker.lock.LockChecker',
      'org.checkerframework.checker.nullness.NullnessChecker',
      'org.checkerframework.checker.optional.OptionalChecker',
      'org.checkerframework.checker.propkey.PropertyKeyChecker',
      'org.checkerframework.checker.regex.RegexChecker',
      'org.checkerframework.checker.signature.SignatureChecker',
      'org.checkerframework.checker.signedness.SignednessChecker',
      'org.checkerframework.checker.tainting.TaintingChecker',
      'org.checkerframework.checker.units.UnitsChecker',
      'org.checkerframework.common.aliasing.AliasingChecker',
      'org.checkerframework.common.reflection.ClassValChecker',
      'org.checkerframework.common.reflection.MethodValChecker',
      'org.checkerframework.common.returnsreceiver.ReturnsReceiverChecker'
    ]
    extraJavacArgs = [
      '-Awarns'
    ]
    excludeTests = true
  }
```
Checker Framework version is 3.9.1, build command was `./gradlew spotbugs:compileJava`. Spotbugs commit id was `c37cee56387bedef9110cbc8004d59ff08b75d67`. However, after a few minutes I got a heap overflow error. When I commented out the first checker line, thus `org.checkerframework.checker.calledmethods.CalledMethodsChecker` the error was gone. However, when I tried to comment out all other checker lines and keep only this one then the error was gone as well and the analysis was finished in a few minutes. I also tried to increase heap size to 64G, but it did not help either. The machine where I tested has 24 logical threads and 48G of physical memory.

**Comment by mernst** [comment]
This bug report is unreproducible, for the same reasons as #4207.  This bug report appears to be nearly a duplicate of #4207.

**Comment by baloghadamsoftware** [comment]
Hello,

Thank you for your qucik reply. Here are the steps to reproduce:

$ git clone https://github.com/spotbugs/spotbugs.git
$ git checkout c37cee56387bedef9110cbc8004d59ff08b75d67
$ cp _<location of attached build.gradle>_ .
$ ./gradlew spotbugs:compileJava

I also attached the output of the build command to the standard error.

[heap-overflow.zip](https://github.com/typetools/checker-framework/files/5887241/heap-overflow.zip)

And I agree, it is nearly a duplicate of #4207, but there the lack of CalledMethodsChecker changes the symptom from heap overflow to a hang. The reason may be or may not be the same one, so I thought that it is better to report them separately.

Please tell me if you need additional information.

**Comment by baloghadamsoftware** [comment]
Some additional info: Operating system is Ubuntu 18.04.1 LTS, the machine has 2 pieces of Intel Xenon X5670 CPUs which means 24 logical CPU threads. The system has 48Gb RAM. Java version is 11.0.9.1 (OpenJDK). After getting this error the first time I tried to increase the heap using the "export JAVA_TOOL_OPTIONS=-Xmx64g" command before the build. It did not help.

SpotBugs claims that it has to be built with Java 8, but ironically, it cannot be built with Java 8 because it uses the "--release 8" compilation option which is only supported in Java 9 and higher. However this option forces the compiler to behave as Java 8.

**Comment by baloghadamsoftware** [comment]
OK, I modified a gradle config file of SpotBugs a bit to not to use the "--release 8" option so I could build it with Java 8. Using the attached build.gradle it still crashes with heap overflow but a couple of minutes later. However, as long as I watched in htop the whole memory usage of the system was not more than 7.8Gb. Strange.

**Comment by mernst** [comment]
Thank you for the additional information.  That is helpful.

1. The Checker Framework manual says to [start small](https://checkerframework.org/manual/#get-started-start-small), with one specific property that matters to you.
The manual also says that you need to annotate the code before running a checker.
Can you explain why you are running multiple checkers on unannotated code?
What is your goal?

2. The problem is that you did not provide Java with enough memory.  I determined this from the output you provided, which contains:

```
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
warning: Memory constraints are impeding performance; please increase max heap size.
error: SourceChecker.typeProcess: unexpected Throwable (OutOfMemoryError) while processing /home/edmbalo/spotbugs/spotbugs/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/type/TypeFrameModelingVisitor.java; message: Java heap space
  ; The Checker Framework crashed.  Please report the crash.
  Compilation unit: /home/edmbalo/spotbugs/spotbugs/spotbugs/src/main/java/edu/umd/cs/findbugs/ba/type/TypeFrameModelingVisitor.java
```

Could you please do as the messages suggest, and provide a larger maximum heap size?

It sounds like you tried to do that, but there was something wrong with the way you invoked the JVM so it did not work.
That is a JVM problem, not a Checker Framework problem.  I am sorry I cannot help with that.
However, I have opened a [pull request](https://github.com/typetools/checker-framework/pull/4217) to show the max heap size, to help diagnosing how the JVM was started.  Hopefully that will help you resolve the JVM invocation problem.

3. If you run one checker at a time, that will use less memory than running all the checkers simultaneously.

**Comment by baloghadamsoftware** [comment]
Thank you for your answer!

Please let me explain a bit why we are doing this.

Our main goal is to provide our Java developers with a toolset (consisting of various static analysis tools) to check their existing and future code. We are especially interested in checking errors described in the SEI CERT Coding Standards. We met The Checker Framework there, among the suggested tools by SEI CERT. We became interested primarily in the Tainting Checker but we are examining the other checkers as well.

Generally, we cannot expect that our developers annotate all their code (especially the code that already exists) using Checker Framework-specific annotations. Instead, we try to find out which of the checkers work on unannotated code with annotated JDK or on code that uses (quasi)standard annotations, such as javax.annotation.* or javax.validation.constraints.*. For example, the Tainting Checker seems to be useful once more classes in the Annotated JDK become annotated for tainting. Another checker we could potentially use is the Nullness Checker since annotations such as javax.annotation.Nonnull and javax.validation.constraints.NotNull are quite popular.

Of course, we began our evaluation by running one checker at a time. However, we also tried to run multiple checkers at once and then we got this heap overflow error.

The strange thing is that I tried to set JAVA_TOOL_OPTIONS to -Xmx64g and when querying java it claims that the maximum heap size is 64Gb. Also, when starting the build javac prints that is uses this option. However, the total memory usage on the machine is 7.8Gb at the peak. I will try to find out why this happens.

**Comment by mernst** [comment]
Thanks for the explanations.

It's weird that the JVM is not using all the memory that you made available to it.  I [further expanded](https://github.com/typetools/checker-framework/commit/8acaf8278b71e857bd903fb63aada9291cfc44a8) the information in the GC diagnostics, to help with noticing and diagnosing that problem.  This does seem to be a JVM problem rather than specific to the Checker Framework, but let us know if there is anything we can do in the Checker Framework to mitigate it.

If you want to evaluate the suitability of a type checker for a project, I have two suggestions.

 * You might find it easier to run one checker at a time, because then you can easily see how many warnings are specific to that checker.  When you run multiple checkers, you would have to determine which errors are related to which checkers.  (Maybe you have already written programs to do that for you.)

 * I also suggest that you try using [type inference](https://checkerframework.org/manual/#wpi-one) -- again, probably one checker at a time.  It infers some of the necessary annotations, and thus its output can be more useful than a checker's output on an unannotated program.

**Comment by baloghadamsoftware** [comment]
I made some experiments by exponentially allocating memory in a Java program. The -Xmx64G worked as expected. I wonder why it is not taken into account when Gradle executes javac with several checkers as annotation processors.

Thank you for the suggestions! I tried to use type inference, experienced some interesting things, but I think I should not discuss it with you in this particular ticket.

**Comment by mernst** [comment]
Ádám, thanks for doing those experiments.
Does that suggest a problem in the [Checker Framework Gradle plugin](https://github.com/kelloggm/checkerframework-gradle-plugin) that should be reported there?  Or is a Gradle issue?

Your feedback on type inference would be welcome.  Those scripts are new (as of Checker Framework 3.9.0) and we are actively working to improve them.

**Comment by baloghadamsoftware** [comment]
After lots of experiments, setting _JAVA_OPTIONS solved the problem.
