### ISSUE TITLE
Since v3.8.0 SuppressWarnings requires lower-cased key

### ISSUE THREAD

**Issue by ahubold** [typetools/checker-framework#4226]
I'm trying to upgrade a custom checker to a recent version of the Checker Framework, but with the step from 3.7.1 to 3.8.0 there's an unexpected change in keys for SuppressWarnings. 

My custom checker is annotated with `@SuppressWarningsPrefix("PersonalData")` and until 3.7.1 I can use `@SuppressWarnings("PersonalData")` to suppress errors in code.

Since 3.8.0 this does not work anymore. Instead, it seems I have to use the lower-case form: `@SuppressWarnings("personaldata")` works. It would be good if I could avoid this breaking change for usages of our custom checker.

Is this an intended change? I haven't found anything about this in the release notes of 3.8.0.

I noticed however that you lower-cased keys in the code as well, so this might be related: https://github.com/typetools/checker-framework/commit/694db511b46a79d2390bd4883ebbf2e59e341129

**Comment by mernst** [comment]
Thanks for reporting this bug, and sorry for the inconvenience to you.

It was intentional to support only one casing for each `@SuppressWarnings` key.  (Multiple different ways to achieve the same effect is confusing for users and error-prone for tooling.  Support for multiple casings was never documented in the manual.  Therefore, it wasn't put in the release notes because it isn't a change to the Checker Framework as documented.)

It was **not** intentional to force that to be lowercase; the Checker Framework should respect the casing in a `@SuppressWarningsPrefix` annotation.
I have opened a pull request to fix that.

If it is convenient for you to test it, that would be helpful, but is not essential.

**Comment by ahubold** [comment]
I'd test it, but sadly I have problems building the CF from source. `./gradlew assemble` fails with a compile error that it cannot find `scenelib.annotations.el.TypePathEntry`. I tried to follow the instructions for building from source, and also used `./gradlew cloneAndBuildDependencies`, which worked for me in the past, but I had to give up now.

Anyway, thanks for the prompt response and fix. I'll definitely try it out when a release comes out.

**Comment by mernst** [comment]
I'm sorry you are having trouble building the CF.  It's working for me and in continuous integration, so something must be different about your environment.

When you say you cannot build the CF from source, do you mean master, or do you mean your own fork?  I suspect it's your own fork.  In that case, you need to either pull master into your fork, or you need to use an older version of the `annotation-tools` repository (use `git checkout 3.9.17` in the `annotation-tools` repository).

The reason is that `annotation-tools` version 3.10.0 is incompatible with `annotation-tools` version 3.9.17.  `checker-framework` version 3.10.0 and later requires `annotation-tools` 3.10.0.

**Comment by ahubold** [comment]
The fix works for me. Thank you. 

(I had to make a fresh Git clone to build it. In my previous attempt, the sibling repositories weren't up to date)
