### ISSUE TITLE
Update to checker > 3.9.0 has the potential to introduce runtime failure

### ISSUE THREAD

**Issue by rkraneis** [typetools/checker-framework#4355]
Unfortunately the change introduced in version 3.10.0
> Moved utility classes from `checker-qual.jar` to the new `checker-util.jar`.
Also, added `util` to the end of all the packages of the utility classes.

also changed the package said utility classes reside in (without deprecating them earlier on).
This can even lead to runtime failure, if utility classes have been used in a library project and the project depending on said library updates its version of checker-framework.

Was this problem considered or is the usage of those utility classes discouraged? (We now basically need to decide if we have to ban usage of checker provided helper classes in production code if such restructuring is expected).

On a related note: is the version meant to be semantic (as in https://semver.org/spec/v2.0.0.html) or only trying to communicate the severity of changes on a best-effort basis?

**Comment by mernst** [comment]
We should have deprecated the old utility classes and retained them for a few releases.  That is our policy for disruptive changes such as this one, we have done it in the past, but we simply forgot to do it for this release.  I apologize for our oversight and for the inconvenience to you.

We currently use the following versioning scheme:
 * the major version indicates major new features,
 * the minor version is changed for incompatible API changes (this is nearly every release, since the API includes all user-visible functionality and all the methods that a type system might invoke), and
 * the patch version is changed for adding functionality or bug fixes.

I'll add documentation of this convention.
By that definition, the movement between packages was legal because the minor version was incremented -- but again, we should have deprecated the old versions in addition to incrementing the version number.

Thanks for catching this mistake.

**Comment by rkraneis** [comment]
Thank you for the explanation. In that case, we will not rely on API for our libraries.

**Comment by mernst** [comment]
Could you explain why not?  I noted that it is generally stable, and that the version number indicates when there is a possible change?

**Comment by rkraneis** [comment]
Yes, of course. I guess I should have given a proper rationale.
Assume a library using a certain version of checker and a project consuming said library using a different version of checker. If breaking changes happen quite regularly, we are always forced to keep all projects (libraries and consumers of libraries) on the same version of checker (and update the code accordingly), basically dictated by the shared library. For that reason we try to limit dependencies exported by our libraries to only those that make strong guarantees with regards to backwards compatibility (for example guava, as they promise to "never remove stable API"), so that we can usually resolve differing library versions just to the latest.
API for us currently only means Opt and NullnessUtil. We will copy those classes to a our projects.
Maybe checker framework can establish stronger guarantees for API meant to be used by clients, especially if such API is not present in the base checker.jar?

**Comment by mernst** [comment]
> API for us currently only means Opt and NullnessUtil. We will copy those classes to a our projects.

That is a reasonable approach.  These utilities change rarely.

> Maybe checker framework can establish stronger guarantees for API meant to be used by clients, especially if such API is not present in the base checker.jar?

Our guarantee is that the middle version number changes if there is any incompatibility.
However, it is also true that the middle version number might change if there is no incompatibility.  There is a tradeoff:
 * it is helpful to keep the version number the same between checker.jar and checker-util.jar, because it shows which versions are guaranteed to work together.
 * it is helpful to release checker-util.jar less frequently, so it is more apparent to users when there might be a breaking change.

I think you are pointing out the benefits of the latter; I do agree with those benefits.
