### ISSUE TITLE
Error on generic type for parameterized method

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/checker-framework#439]
```
What steps will reproduce the problem?

Compile a class like below using the NullnessChecker:

public class DeleteMe
{

    static <T> T hi(List<T> t)
    {
        throw new RuntimeException(); // doesn't matter
    }

}

What is the expected output? What do you see instead?

Should compile.

Error I see (on the type parameter of the List argument): 

Error:(24, 26) java: [type.argument.type.incompatible] incompatible types in 
type argument.
  found   : T extends @Initialized @Nullable Object
  required: @Initialized @NonNull Object

What version of the product are you using? On what operating system?

Using MacOS, checker-framework version 1.9.2

```

Original issue reported on code.google.com by `renato.a...@twobotechnologies.com` on 2 Jul 2015 at 2:08

**Comment by wmdietl** [comment]
(Thanks to Jonathan for noticing that my replies to the Google Code issue were after the issue tracker was moved. Below a copy of the email copies I still had.)

checker-framework@googlecode.com via googlegroups.com 
Jul 3 (3 days ago)

to checker-framew. 
Updates:
        Status: Invalid

Comment #8 on issue 439 by wdi...@gmail.com: Error on generic type for parameterized method
https://code.google.com/p/checker-framework/issues/detail?id=439

Hi Renato,

you are not using the correct annotated JDK when you run the Checker Framework.
Note the following output:

warning: You do not seem to be using the distributed annotated JDK.  To fix the
  problem, supply this argument (first, fill in the "...") when you run javac:
    -Xbootclasspath/p:.../checker/dist/jdk8.jar

Without the annotated JDK on your bootclasspath, the upper bound of the java.util.List type parameter is defaulted to "@NonNull Object" (in the version you're using; we're working on changing this default).
(Similarly, the warnings about missing enum constants signify that something is wrong with your setup.)

You need to simply add the annotated JDK to the bootclasspath and you'll get the behavior you expect.

cu, WMD.


checker-framework@googlecode.com via googlegroups.com 
Jul 3 (3 days ago)

to checker-framew. 
Comment #9 on issue 439 by ren...@athaydes.com: Error on generic type for parameterized method
https://code.google.com/p/checker-framework/issues/detail?id=439

Hello. I keep coming across problems due to the fact that I will not use the annotated JDK. This is really not a good solution for me. Why should I use a different JDK that I cannot fully trust, cannot distribute to all my development environments without making my environment more complex than it needs to be (or worse, adding it to my source code!)?

If this cannot be fixed, I will have to give up on using this framework. Making the use of your annotated JDK mandatory is a show stopper for me and for any Java environment I can think of that does not consist of a single machine/compiler.\

You guys have a better solution to this which is to use class stubs to provide the required annotations. I am doing this myself at the moment, but you could make these stubs part of your jar and use them by default (but still allowing people to not use them if that makes sense). This will make the 'get started" section of your framework a one-liner: add the jar to the classpath (using Maven, Gradle, even javac!) and enable the annotation processor you want to use.

No need to download anything manually, point to absolute paths, set env variables or other horrible things.


checker-framework@googlecode.com via googlegroups.com 
Jul 3 (3 days ago)

to checker-framew. 
Comment #10 on issue 439 by wdi...@gmail.com: Error on generic type for parameterized method
https://code.google.com/p/checker-framework/issues/detail?id=439

The annotated JDK is only used for type checking. There is no run-time dependency.
The annotated JDK does not even contain method bodies - it is created from ct.sym and only contains annotated signatures.
Given that you already trust the Checker Framework annotation processors, there is no reason to not trust the annotated JDK.
We considered several alternatives and the annotated JDK is the best option; we are making its usage as easy as possible.
