### ISSUE TITLE
-AsafeDefaultsForUnannotatedBytecode causes Checker Framework crash

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#442]
1. clone [plume-lib](http://mernst.github.io/plume-lib/):  `git clone https://github.com/mernst/plume-lib.git`
2. uncomment line 154 in plume-lib/java/Makefile
3. run `make`

The Checker Framework suffers multiple NullPointerExceptions and issues nonsensical errors.  An example of output appears at https://gist.github.com/mernst/e2a5e97d6c109234de7b

**Comment by JonathanBurke** [comment]
This can be fixed by adding a scope != null check to line 675 in QualifierDefaults.java.  It seems that we added these null-checks so that the `DefaultQualifierInHierarchy` can be applied via the defaulting mechanism even if we have no element for a given type.  The only place that it seems we pass null to the scope constructor parameter is in `postDirectSupertypes` in the Qualifier Framework (hence why this fails on the RegexChecker).  

I can add the above null check but then we have other Qualifier Framework related exceptions.  Perhaps, adding the null check is the right move and then we can close this issue and add a new one for the new errors or just update this issue.

Does anyone have a preference?
