### ISSUE TITLE
-AsafeDefaultsForUnannotatedBytecode seems to give literals undesirable types

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#455]
To reproduce the problem, remove the line

    // @skip-test

from file checker-framework/checker/tests/nullness-safedefaults/ArraysMDE.java and then run

   cd ${CHECKERFRAMEWORK}/checker
   ant -e -find build.xml nullness-safedefaults-tests

**Comment by JonathanBurke** [comment]
Hi Mike,
Is your concern the following diagnostic returned by the compiler:
11: error: (argument.type.incompatible)

I thought that since this class is not `@AnnotatedFor` then the this should not be reported?  Is that correct?  And is that the bug? 

Otherwise, the reason that diagnostic is reported is because locals aren't defaulted using the safe defaults because they aren't viewable from other classes and therefore it doesn't matter if they are annotated or not.   This of course means they get the unsafe defaults which are incompatible with the safeDefaults in this circumstance.

**Comment by mernst** [comment]
Jonathan-

> I thought that since this class is not @AnnotatedFor then the this 
> should not be reported? Is that correct? And is that the bug?

That is a good point.  Can you add a test that explicitly tests that issue?

> Otherwise, the reason that diagnostic is reported is because locals 
> aren't defaulted using the safe defaults because they aren't viewable 
> from other classes and therefore it doesn't matter if they are annotated 
> or not. This of course means they get the unsafe defaults which are 
> incompatible with the safeDefaults in this circumstance.

I think that local variables should be defaulted to the top type, due to 
the climb-to-top rule.  Without climb-to-top, users will suffer hundreds 
of false positives, the behavior will be unnecessarily different from the 
behavior without -AsafeDefaultsForUnannotatedBytecode, and transitioning 
from an annotated library to fully-annotated code will be unnecessarily 
difficult.

                     -Mike

**Comment by JonathanBurke** [comment]
In the Checker Framework meeting we decided:
ArraysMDE should be `@AnnotatedFor`.
I should add a test case that is NOT `@AnnotatedFor` and it emits warnings in method bodies that are suppressed by the -AsafeDefaultsForUnannotatedBytecode/shouldSuppressWarnings mechanism.

**Comment by mernst** [comment]
I have added test cases, they pass, and as far as I can tell this issue can now be closed.
