### ISSUE TITLE
manual entry about spotbugs offensive and innaccurate

### ISSUE THREAD

**Issue by xenoterracide** [typetools/checker-framework#4591]
seems like the entirety of documentaton around this is saying "spotbugs sucks" and "we're awesome"

> The Checker Framework has a more powerful nullness analysis; FindBugs misses some real errors. FindBugs requires you to annotate your code, but usually not as thoroughly as the Checker Framework does. Depending on the importance of your code, you may desire: no nullness checking, the cursory checking of FindBugs, or the thorough checking of the Checker Framework. You might even want to ensure that both tools run, for example if your coworkers or some other organization are still using FindBugs. If you know that you will eventually want to use the Checker Framework, there is no point using FindBugs first; it is easier to go straight to using the Checker Framework.

this is unfair considering that it appears that checkers coverage of the jdk is far from complete. Previous bug that resulted in an NPE using `Path::getParent` (now fixed but not released), was caught by spotbugs, but was not caught by checker or nullaway. Because of this, you can't simply rely on checker framework to catch all NPE's. Now I'm not going to say that spotbugs will catch all NPE's, no analysis tool is perfect.

I think this should be reworded to be more neutral. Also, findbugs is dead, and it doesn't work with jdk 11.

**Comment by mernst** [comment]
Your issue report does not give any examples of offensive or inaccurate text.  It does make two points:
 * you don't understand the paragraph (you didn't quote the previous paragraph, which gives context)
 * there are situations where SpotBugs finds bugs that the Checker Framework does not.

I'll address those issues.

**Comment by mernst** [comment]
It doesn't put down the other tools.  It starts out by saying that different tools have different tradeoffs, it describes them, and it suggests using both.  (All this was true of the text as originally written.)

I'm sorry this hit an emotional chord for you.  Rather than belaboring your interpretation of specific parts of the old text, your comments on the current text would be useful.

Thanks again for reporting a bug that SpotBugs found -- the first such report.  I appreciate being notified about the missing library annotation!
