### ISSUE TITLE
dataflow-shaded artifact includes unshaded dependencies

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#4615]
I was surprised to see that the dataflow-shaded artifact includes unshaded versions of dependencies, namely plume-util and the Checker Framework qualifiers.  For plume-util, I think it should also be shaded.  If it is not, it could lead to future conflicts if a tool using dataflow-shaded and a Checker Framework checker are run simultaneously (if the required versions of plume-util have diverged).

For the Checker Framework qualifiers, the same type of conflict could occur.  Are these classes really required at runtime by the dataflow code?  Or could a `compileOnly` dependency be used for the qualifiers, so they are neither included in the dataflow-shaded artifact nor are they listed as a Maven dependence?  Alternately, if the qualifiers are required at runtime, they could also be shaded in the jar.

**Comment by msridhar** [comment]
Upon further thought, it may be best to shade the `checker-qual` classes as well, even if it's possible to remove them from the jar.  Otherwise, there may be an issue when loading a class in the `dataflow-shaded` artifact if it references a qualifier that gets loaded from a more recent version of the `checker-qual` jar.

**Comment by smillst** [comment]
plume-util should be shaded in dataflow-shaded.jar.  Thank's for pointing that out;  I'll fix it.  plume-util is shaded in checker.jar, so it won't conflict with dataflow-shaded.jar, but it still should be shaded.

Shading checker-qual is a little trickier.  The qualifiers in `org.checkerframework.dataflow.qual` are used by the dataflow framework at runtime.  For example, `org.checkerframework.dataflow.util.PurityUtils` uses the purity qualifiers to check for purity annotations in the code that dataflow is analyzing.  It does that check using the class of the purity qualifiers, so that class need to be unshaded.  It could be rewritten to use a string rather than the class.   There may be other places in dataflow that use the qualifiers a runtime. So, I think it's possible to change dataflow to use a shaded version of checker-qual.jar, but it would require changes to the code.

**Comment by msridhar** [comment]
Thanks, @smillst!  Yes, since the Checker qualifiers are used at runtime, shading those will be tricky.  Probably the API for existing qualifiers is quite stable, so I think running into a conflict issue may be unlikely.  As a longer-term goal it may be good to get to the point where shading of the qualifiers is possible.

I had a related question.  What is the reason for including `dataflow` and `javacutil` classes inside the `checker` artifact?  I know these are part of the API of `checker`, but that could also be expressed in Maven / Gradle dependencies (see #4612).  We recently had an issue with a class version conflict between NullAway and the Checker Framework (uber/NullAway#462), and it would have been easier to discover the root cause if these classes were not included inside the `checker` artifact (since then, I _think_ printing the Gradle dependency tree would have shown a more recent version of `dataflow` getting pulled in).

**Comment by smillst** [comment]
For dataflow-shaded.jar, I'll make checker-qual a dependency of the artifact rather than included in the jar.  That should make it easier to detect conflicts.

> What is the reason for including dataflow and javacutil classes inside the checker artifact?

I don't think there's a reason for this.  I'll make them dependencies.

**Comment by smillst** [comment]
I shaded plume-util in https://github.com/typetools/checker-framework/pull/4639. I still need to make checker-qual a dependency rather than included in the fat jar.

**Comment by msridhar** [comment]
Thanks, @smillst!  FYI I commented on the approach you took there: https://github.com/typetools/checker-framework/pull/4639#discussion_r627547930

**Comment by msridhar** [comment]
@smillst is this fixed now, or at least as fixed as it ever will be given dataflow's runtime use of certain annotations?

**Comment by msridhar** [comment]
Going to go ahead and close this as I think it's fixed as best as we can expect
