### ISSUE TITLE
Suggestion: enable "Always suggest updating pull request branches" on GitHub

### ISSUE THREAD

**Issue by msridhar** [typetools/checker-framework#4965]
It might be nice to enable the "Require branches to be up to date before merging" setting in the branch protections for the master branch.  This would correspond to the "Strict" setting documented here:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-status-checks-before-merging

On the plus side, this would guarantee (modulo non-deterministic CI checks) that after a PR is merged, CI will be green for the master branch.  The downside is that if you have several PRs you'd like to land in quick succession, this can slow things down, since you need to wait for CI to pass after merging back `master` to each PR in turn.  But in such cases, an administrator can just override the checks and merge the changes, if she is confident the changes are safe.

A nice thing about enabling this feature is that GitHub then adds a button you can click on a PR to merge in the latest `master` branch when it is out of date.  It looks like this:

<img width="651" alt="Screen Shot 2021-11-16 at 9 51 45 AM" src="https://user-images.githubusercontent.com/193105/142038936-11c8bbe4-3402-4f81-b9e7-8636b094ac24.png">

I've found this button to be quite handy for PRs on the WALA repo.

**Comment by mernst** [comment]
Manu, thanks for this suggestion.  I agree that it solves a problem.  After discussion with Suzanne, I'm going to hold off on merging it for now because we have infrequently observed problems with conflicting parallel pull requests, but we have definitely had problems with slow CI, which this would make worse.  I'll keep it in mind for the future if conflicting or out-of-date merges become more of a problem.

I wish there was to enable the "Update branch" button without requiring branches to be up to date before merging.

**Comment by mernst** [comment]
Thanks for noticing this!  I have enabled the tickbox, in checker-framework, annotation-tools, and stubparser (and in some of my other projects).
