### ISSUE TITLE
Annotations that should never be used in source code -- except on bounds

### ISSUE THREAD

**Issue by smillst** [typetools/checker-framework#515]
Several checkers' top and/or bottom annotations are not supposed to be written in source code, but on occasion it is necessary to write the top or bottom annotation on a bound. See [this discussion](https://groups.google.com/forum/#!topic/checker-framework-discuss/u42B7k3hb10) for an example.

We should correct the manual, so that it mentions these possible uses.

**Comment by wmdietl** [comment]
We should also update those qualifiers I assume. Just updating the manual will not fix the issue.

At the moment most type systems use the same defaults for upper and lower bounds of wildcards, that is:
`List<? extends Object>`
`List<? super Object>`
both use the same default qualifier. This is nice and consistent.
Would it be easier to use to use the bottom type for "super" bounds? We can express this using org.checkerframework.framework.qual.DefaultLocation.LOWER_BOUNDS.

**Comment by mernst** [comment]
I agree that using the bottom type for super bounds makes sense -- probably as a default for all type systems.

**Comment by mernst** [comment]
I have separated two other concerns into issue #520 and issue #521.

What remains for this issue is to provide a new meta-annotation (say, called `@TargetTrees`) to indicate locations a particular qualifier is not intended to be written, even though such locations are compatible with the annotation's `@Target` meta-annotation.

An example is that many type systems' bottom qualifier (those with "Bottom" in their name, including `@BottomAll` from issue #521) should only be written on a wildcard super bound.

The `@TargetTrees` should take as an argument a list of `Tree.Kind` locations at which the annotation is permitted.

If a programmer writes an annotation at any other location that is not listed in the `@TargetTrees` meta-annotation, then the Checker Framework issues a warning.  This warning may be suppressed.

The `@TargetTrees` meta-annotation should be added to a number of existing annotations with "Bottom" in their name, and likewise for some with "Top" or "Unknown" in their name.

**Comment by smillst** [comment]
Parts 1 and 2 were completed in pull request #533.

**Comment by jthaine** [comment]
Part 3 is now critical to support the Lock Checker's @GuardSatisfied annotation, which may only be written in certain locations.

**Comment by jthaine** [comment]
When resolving this issue, remove the following method from the Lock Checker: LockVisitor.issueErrorIfGuardSatisfiedAnnotationInUnsupportedLocation

**Comment by wmdietl** [comment]
@topnessman started working on enforcing TargetLocations.

We have a question about compound types.
Let's say we have type annotations TA and TB that have empty TargetLocations annotations, so they are not allowed to be used in source.
Then let's assume we have a field `@TA List<@TB Object> l`.
The use of TA is invalid, because it is in a FIELD location, but TA doesn't contain FIELD in the TargetLocation.

Should the use of TB in the type argument be valid or not?
I would say we should forbid uses of an annotation if the top-level construct is not in the TargetLocations.
Alternatively, one could say that the type argument position is a different type use and should be covered by a different TypeUseLocation constant. In particular, the documentation for FIELD states "Apply default annotations to all unannotated raw types of fields." The "raw type" implies that it doesn't apply to type arguments.

(As an aside: we use TypeUseLocation for things besides defaulting, so its documentation needs to be updated.)

Two options:
1. We say the TypeUseLocations include type arguments, arrays, and other composites
2. We introduce separate TypeUseLocations for composite types
a. as refinements of the current TUL, e.g. FIELD_TYPE_ARGUMENT, FIELD_ARRAY, etc.
b. only on the composite type level, e.g. just adding TYPE_ARGUMENT, ARRAY, etc.

Option 1 probably doesn't work for defaulting, were we don't want the same defaults for main modifiers and type arguments, e.g. for a local variable type.
Introducing different interpretations for TypeUseLocation for defaulting and TargetLocations is also not nice.

**Comment by smillst** [comment]
>I would say we should forbid uses of an annotation if the top-level construct is not in the TargetLocations.

I disagree.  One motivation for this feature is to allow annotations on upper or lower bounds, but not elsewhere.  If TB is meta-annotated with `@TargetLocations(UPPER_BOUND)` then `List<? extends @TB Object>` should be legal even if it is the type of a field. 

>Two options:
>2. We introduce separate TypeUseLocations for composite types
>b. only on the composite type level, e.g. just adding TYPE_ARGUMENT, ARRAY, etc.

This is the option I would prefer.  TypeUseLocation already has some composite types such as UPPER_BOUND and LOWER_BOUND.

**Comment by wmdietl** [comment]
> I disagree. One motivation for this feature is to allow annotations on upper or lower bounds, but not elsewhere. If TB is meta-annotated with @TargetLocations(UPPER_BOUND) then List<? extends @TB Object> should be legal even if it is the type of a field.

So should it be: an annotations TargetLocation must contain at least one of the TypeUseLocations observed when traversing the tree from the annotation usage towards the root?
That is, if TB is FIELD or UPPER_BOUND, it is valid to use in `List<? extends TB Object> f`.

However, what about `List<@TB Object>`. Should that use of TB count as FIELD?
My argument was that this should be forbidden if TB is not meta-annotated with TargetLocation FIELD.
Do you disagree with that?


> This is the option I would prefer. TypeUseLocation already has some composite types such as UPPER_BOUND and LOWER_BOUND.

I wouldn't call those composite types. The wildcard bounds are parts of a composite type. Type variable bounds are not part of a composite type at all.

**Comment by topnessman** [comment]
I vote for solution 2.b. 

> b. only on the composite type level, e.g. just adding TYPE_ARGUMENT, ARRAY, etc.

Remember we have an OTHER enum constant in TypeUseLocation? That's the best indication of the need of adding separate locations, i.e., TYPE_ARGUMENT, ARRAY_COMPONENT for composite types. 
Based on the approach, 
In  `@Fobid1 List<@Forbid2 String>`: We forbid `@Forbid2` because `@Forbid2` isn't declared to be used on TYPE_ARGUMENT; But not because it's annotated on type argument of a type of field. '@Forbid2 String' is on somewhat "type argument location", not on field. What if there is another local variable whose type is  `@Fobid3 List<@Forbid2 String>`, we should also forbid `@Forbid2`. 
Type argument might also be recursively composite, meaning that there exist `@Forbid4 List <@Forbid5 ArrayList <@Forbid6 Node>>`. Both are type uses on TYPE_ARGUMENT, because `@Forbid5` is on type argument of List,  and `@Forbid6` is on type argument of ArrayList.
The above logic also applies for array component type.
Climbing up till the root doesn't seem to be precise enough for me. And 2.a seems too cumbersome for me.

**Comment by mernst** [comment]
I don't fully understand the alternatives.  For example, I'm not sure what "include" means in option 1, and in option 2 I think the the discussion of "composite types" is really a discussion of type components rather than the entire composite type.

However, I think I agree with Suzanne and Mier.
When determining the validity of a type annotation, I feel the Checker Framework should take into account only the exact location at which it is written, and not depend on enclosing elements.
This is also what I think is consistent with the current documentation.

Do you have an example in mind where that approach is insufficiently precise?
(I suspect that is what has raised this issue.)

**Comment by smillst** [comment]
>So should it be: an annotations TargetLocation must contain at least one of the TypeUseLocations observed when traversing the tree from the annotation usage towards the root?
That is, if TB is FIELD or UPPER_BOUND, it is valid to use in List<? extends TB Object> f.
However, what about List<@TB Object>. Should that use of TB count as FIELD?
My argument was that this should be forbidden if TB is not meta-annotated with TargetLocation FIELD.
Do you disagree with that?

Yes I disagree, the use of `@TB` in `List<@TB Object>` is only allowed if `@TB` has not `@TargetLocation` or if it is `@TargetLocations(TypeUseLocation.TYPE_ARGUMENT )` assuming we added that location.  If  `List<@TB Object>`  is the type of a field and `@TB` is meta-annotated with `@TargetLocations(FIELD)` it is still should not be allowed.

**Comment by mernst** [comment]
I concur with Suzanne.

**Comment by wmdietl** [comment]
I'm fine with implementing option 2b: we add new coarse-grain TypeUseLocations for type arguments, arrays, etc. and then enforce correct usage in TargetLocation.
I'm not sure how natural that specification will be in the end. E.g. do I really want to enforce the same type argument default for all possible uses of a type argument?
But we can wait and see whether we need that refinement.
Mier, does this answer all your questions about how to implement this?

**Comment by topnessman** [comment]
Prof, we are only adding these two locations into TypeUseLocations. I think we don't necessarily also want to add default qualifiers for these two locations. 

Currently, the documentation is also strong related to QualifierDefaults, which I think is not proper. Because TypeUseLocations are only locations, it should not be too related to either implementation, i.e. QualifierDefaults and TargetLocationVisitor(I created to enfore @TargetLocation)

**Comment by mernst** [comment]
Closed in favor of #1908.
