### ISSUE TITLE
Poor Nullness Checker performance when code has many assignments

### ISSUE THREAD

**Issue by mernst** [typetools/checker-framework#536]
Type-checking file checker-framework/checker/tests/nullness/AssignmentPerformanceTest.java takes about 10 minutes even though the only code in it is 150 assignments.

**Comment by stefanheule** [comment]
I looked into this, and I believe this is the problem (this is at least a large part of the problem, there might be other sources of inefficiencies):

Whenever "this" (implicitly or explicitly) is used in a constructor, we need to compute the type of "this".  In the Initialization type system, the type of this is either @UnderInitialization or @UnderInitialization(CurrentClass), depending on whether all fields have been initialized or not (and if no fields are @NotOnlyCommitted).  This is done in InitializationAnnotatedTypeFactory.setSelfTypeInInitializationCode, and we use the store directly before the "this" reference to see what fields are initialized (using a call to getStoreBefore).  This call takes O(n) time where n is the number of statements before the current one.  So, in a constructor of n statements, we do O(n^2) work for type-checking, just because of this.

Here's some explanations of why things are the way they are:  The dataflow analysis is done once for the whole constructor.  For space efficiency reasons, we don't want to cache a store for every statement, but rather we store the store before every basic block (and a few other special places, like method exits).  To get any store for a program point inside a basic block, we can just take the store before the basic block, and run the transfer function a few times.  This works well if the following assumptions are true:

- Stores inside basic blocks aren't asked for too often.  I think this is usually true, but it is not true for the selfType computation above.
- Basic blocks are small.  Again, this is probably mostly true, but the test case has 150 statements in a single basic block.

# Solution

A solution most likely will involve caching information a bit better.  For instance, one could cache just one bit for every statement that indicate whether all fields are initialized at this point.  This is very little information (and only has to be done for constructors even), and is enough to avoid the O(n^2) problem above.

I won't be able to implement a fix at the moment.
