### ISSUE TITLE
The Called Methods Checker treats methods as "called" even if they fail

### ISSUE THREAD

**Issue by Calvin-L** [typetools/checker-framework#5767]
The called methods checker documentation does not explain how it treats exceptions. In the example below (and I suspect in general), it treats a method as "called" even if that method throws an exception.

If that is intended behavior then this issue can be closed, and I would be happy to help improve the documentation.

However, it is a bit of a shame for my use case. If a method throws an exception then some important code in the method might have been skipped. I was hoping to use `@RequiresCalledMethods` to mean "these methods ran to completion without error"---in other words, that they finished all the work they were supposed to do.

I am using Checker Framework version 3.33.0.

```java
import org.checkerframework.checker.calledmethods.qual.RequiresCalledMethods;

import java.security.SecureRandom;
import java.util.Random;

public class CalledMethodsCheckerTest {

    public static void main(String[] args) {
        var service = new Service();

        try {
            service.initialize();
        } catch (Exception ignored) {
            // Oops!  Ignoring the exception is a huge mistake.
        }

        // I would like to prove that run() never throws IllegalStateException.
        // The called methods checker accepts this code, but it can still throw
        // IllegalStateException!  :(
        service.run();
    }

}

class Service {

    private final Random rand = new SecureRandom();
    private boolean initialized = false;

    void initialize() {
        if (rand.nextBoolean()) {
            throw new RuntimeException("fail");
        }
        initialized = true;
    }

    @RequiresCalledMethods(value="this", methods={"initialize"})
    void run() {
        if (!initialized) {
            throw new IllegalStateException();
        }
    }

}
```

**Comment by kelloggm** [comment]
This is the intended behavior (and it is important to keep it, to support the Resource Leak Checker: `Closeable#close()` can throw exceptions, but the Resource Leak Checker should still treat the object as having been closed). I'm sorry it doesn't match your expectations, and I'd definitely appreciate some help in clarifying the docs!

It also probably wouldn't be too hard to add support to the Called Methods Checker for the use case you're describing (maybe guarded behind a command-line flag), because the current behavior actually requires special support in the checker - e.g., [this code](https://github.com/typetools/checker-framework/blob/959d0114d97b585c9d5ad75dd7638d11d7b5c64a/checker/src/main/java/org/checkerframework/checker/calledmethods/CalledMethodsTransfer.java#L67) in `CalledMethodsTransfer` would just need to be locked behind an option to get the behavior you're looking for.

There is more context/discussion of this choice on [this PR](https://github.com/typetools/checker-framework/pull/4683), which made the change.

**Comment by Calvin-L** [comment]
I promise I read the docs very carefully, but I see that PR includes exactly the text I would have added! Sure enough, I just missed that sentence in my first read. So, I don't think the docs need updating, only my brain.

> `Closeable#close()` can throw exceptions, but the Resource Leak Checker should still treat the object as having been closed

That's a great point, and I definitely agree that's how it should work.

> It also probably wouldn't be too hard to add support to the Called Methods Checker for the use case you're describing (maybe guarded behind a command-line flag)

I'm not sure I want that, especially if it breaks the Resource Leak Checker.

If I understand correctly:

| | Type annotation | Precondition (my program requires that...) | Postcondition (my program ensures that...) |
|----|----|----|----|
| `m()` will be called | `@MustCall` | (not needed?) | (not needed?) |
| `m()` was called | `@CalledMethods` | `@RequiresCalledMethods` | `@EnsuresCalledMethods` |
| `m()` returned without exception | :x: | :x: | :x: |

I think what I really want is annotations and checking for the bottom row, perhaps with names like `@CompletedMethods`, `@RequiresCompletedMethods`, and `@EnsuresCompletedMethods`.

**Comment by Calvin-L** [comment]
Closing since I don't think any changes to the docs are actually needed.

**Comment by mernst** [comment]
@Calvin-L Do you want to open an issue for a feature request for the "returned without exception" case?
