### ISSUE TITLE
Comparing type variable to int[] fails

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#577]
The framework occasionally (thrice in the merged annotated JDK) throws an exception with a message about "Incomparable types".  For instance, `javac -processor nullness -AprintErrorStack `[java/util/stream/IncomparableTypes.java](https://gist.github.com/dbrosoft/25391fc28ad992be0d1c) twice prints
```
error: Incomparable types ( T_ARR extends Object, int [])visitHistory = VisitHistory(  )
```
followed by a stack trace.

**Comment by smillst** [comment]
Added test case checker/tests/nullness/Issue577.java:
````
class Banana extends Apple<int[]> {
    class InnerBanana extends InnerApple {
        @Override
        // checking this override causes error
        void foo(int[] array) {
        }
    }
}

class Apple<T> {
    class InnerApple {
        void foo(T param) {
        }
    }
}
````

More of the stack trace:
````
error: Incomparable types ( T extends @Initialized @Nullable Object, @Initialized @NonNull int @Initialized @NonNull [])visitHistory = VisitHistory(  )
  Compilation unit: Imcop.java
  Exception: java.lang.Throwable; Stack trace: org.checkerframework.framework.source.SourceChecker.errorAbort(SourceChecker.java:683)
  org.checkerframework.javacutil.ErrorReporter.errorAbort(ErrorReporter.java:28)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.defaultAction(AbstractAtmComboVisitor.java:36)
  org.checkerframework.framework.type.visitor.AbstractAtmComboVisitor.visitTypevar_Array(AbstractAtmComboVisitor.java:444)
````

**Comment by dbrosoft** [comment]
The fenum checker crashes on Issue577.java as well.

**Comment by smillst** [comment]
asMemberOf is not substituting the type variable declared in an outer class.  I'm working on fixing this.

**Comment by smillst** [comment]
The branch issue577 (see 381eea5d1b6e0ec5d927fd981c90e02dfc9125c6) fixes for this issue, however, it cause Regex to issue wrong errors on plume-lib. (Test case included included in [tests](https://github.com/typetools/checker-framework/blob/381eea5d1b6e0ec5d927fd981c90e02dfc9125c6/checker/tests/nullness/Issue577.java))  I think these new errors are because AnnotatedDeclaredType#getEnclosingType() returns AnnotatedTypeMirrors that have no annotations.  I created #724 is tracking this issue.
