### ISSUE TITLE
failed assertion in CFGBuilder

### ISSUE THREAD

**Issue by dbrosoft** [typetools/checker-framework#671]
[Issue671.zip](https://github.com/typetools/checker-framework/files/226898/Issue671.zip) contains a source file `java/lang/invoke/MemberName.java`, an executable script `issue671` that invokes the Checker Framework, and a stack trace `trace.txt` that contains the result of invoking `issue671`.  The script executes the following command:
```sh
java -jar $CHECKERFRAMEWORK/checker/dist/checker.jar\
 -Xbootclasspath/p:$CHECKERFRAMEWORK/checker/dist/jdk8.jar -processor igj\
 -Anocheckjdk -Aignorejdkastub -AuseDefaultsForUncheckedCode=source\
 -AprintErrorStack java/lang/invoke/MemberName.java
```
First line of the trace:
```
org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseThree.process(CFGBuilder.java:749)
```

**Comment by smillst** [comment]
I added a test case here: framework/tests/all-systems/Issue671.java
The Nullness and Value Checkers also crash.

**Comment by stefanheule** [comment]
There was a bug in phase 1 of the CFGBuilder.  Basically, the first phase creates a list of nodes, and labels some locations in this list with particular labels.  This is necessary because when we first create some special nodes like jumps we don't know the target of that jump yet, so we just give it a name (a label), and later point that label to the right place in the list.  Then, we compute a list of leaders (which will determine where the basic blocks start) and build the CFG from there.  So far, so good.

During this process, we sometimes add nodes to the list not just at the end, but also in the middle of the list.  However, this causes the labels that point into the list (they just use an integer index) to be off by one now, if they point to a node after the insertion point.

Because of this, we get a very wonky list, which caused the assertion failure.  Honestly, I'm a bit surprised this hasn't cause trouble earlier, but I guess we normally insert close to the end (?).

Fixing the bug was easy, finding it not so much...

**Comment by wmdietl** [comment]
Thanks for debugging and fixing this!
