### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by AFulgens** [typetools/checker-framework#680]
Dear Checker Framework Team,

You do an extremely good job about declaring the licenses for the different parts of your code, still I would like to ask some more clarification regarding maven builds. Namely:

In the [LICENSE.txt](../blob/master/LICENSE.txt) you say that in general it is GPL, but the annotations ("all the parts [...] that you might want to include with your own program") are MIT. So far so good.
Now, building with maven. In the [maven-plugin readme](../blob/master/maven-plugin/README-developers) you have a broken link, i.e., http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#maven-plugin. So instead of that, one reads the [corresponding part of the manual](http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#maven), where you see the dependency for the aforementioned annotations **and** the checker itself.
Of course, the checker itself will not end up in your build, it is just *used for building*, and you [clearly state](http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#credits) that "Just as compiling your code with javac does not infect your code with the GPL, type-checking your code with the Checker Framework does not infect your code with the GPL.", still it will end up in your maven dependency tree, and if you run `mvn license:add-third-party`, it will show up as a GPL dependency, which for some lawyers may be problematic.
As I have a multi-module project, I tried not including the dependency in the modules only in the parent (so `mvn license:aggrate-add-third-party` won't show it), but then you get a compile time error, namely that `error: Annotation processor 'org.checkerframework.checker.nullness.NullnessChecker' not found`.

I wanted to circumvent the issue with using the plugin instead of depending on the checker itself, but the link in the [README](../blob/master/maven-plugin/release/README-plugin) is the same broken one as mentioned earlier. After this, I tried to reverse-engineer the usage of the plugin itself based on the readme, but then again I see that although you have a release prepared a month or so ago, on Maven Central, the latest version is 1.7.5; at this point I gave up the reverse-engineering effort.

Any clarification, suggestion would be welcome.

**Comment by mernst** [comment]
Thanks for your message.  I'm sorry for the confusion.

I fixed the broken link, thanks.  It should be http://types.cs.washington.edu/checker-framework/current/checker-framework-manual.html#maven

You said that the latest release on Maven Central is 1.7.5, but I see version 1.9.13, using the link from the Checker Framework manual:
http://search.maven.org/#search\%7Cga\%7C1\%7Corg.checkerframework
Maybe you are using the wrong artifact and so you aren't seeing the latest version.  Can you tell me what artifact you are using and where you got that link?

If I understand correctly, the problem is that a laywer may not understand the meaning of the output of `mvn license:add-third-party`.  Actually, I'm not sure I do either!  Its [documentation](http://www.mojohaus.org/license-maven-plugin/aggregate-add-third-party-mojo.html) doesn't say what it does nor what it outputs, and the [one sentence](http://www.mojohaus.org/license-maven-plugin/examples/example-thirdparty.html) elsewhere isn't adequate.

My guess is that `mvn license:add-third-party` lists all the dependences and you want to show a lawyer a shorter list that only includes run-time dependences, not build-time dependences.

Here are some options:
 * Non-technical solutions:
    * explain the meaning of the tool output to the lawyer, or find a better lawyer  :-)
    * show what is in the output artifacts, which doesn't include the Checker Framework proper but only the MIT-Licensed checker-qual.jar
 * change `mvn license:add-third-party` to understand the distinction between build-time and run-time dependences
 * avoid the Maven dependency.  Download the Checker Framework directly from its website rather than via Maven, and then use it directly.  I don't know whether something like this would work in your `pom.xml` file or you need to do something more elaborate:  https://github.com/typetools/commons-bcel/commit/fdbc708447d0e6ce58f16830084f62c0b62ce3ff

**Comment by AFulgens** [comment]
Thank you for your response. Not really a confusion from mine/your part, but one from the legal side :)

Thanks for fixing the link. About the version in Maven Central: I was referring to the version of the [checkerframework-maven-plugin](http://search.maven.org/#artifactdetails|org.checkerframework|checkerframework-maven-plugin|1.8.2|maven-plugin), not the framework itself. Even then there is a PEBKAC on my behalf, the current version is 1.8.2, I don't know why I found 1.7.5 (maybe I was so silly that I looked on a mirror and not the Maven Central?). Never mind that note of mine.

You understood my problem correctly. I did some more digging, and here are my findings on the matter:
- the output of `mvn license:add-third-party` is simple: the plugin parses the dependency tree, and collects the content of the license tag**s** in **every** dependency it finds
- the `mvn license:aggregate-add-third-party` is used in multi-module projects and it's simply a merge of the output `mvn license:add-third-party` for all modules

The root of the problem is essentially that in maven there is no way to define "built-time only" dependencies, there is simply no [scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html) for it. If there would a scope for this, one could simply [exclude that scope](http://www.mojohaus.org/license-maven-plugin/add-third-party-mojo.html#excludedScopes) for the license plugin.

A reflection on the options you proposed:
- Non-technical solutions:
  - *explain it to the lawyers...* be glad, if you don't have to deal with corporate lawyers on a regular basis :)
  - *show what is in the output artifacts...* that's essentially a good solution, however I haven't found an off-the-shelf solution which can be easily integrated into a maven-based CI-flow; apart from the workaround I will describe below
- *change the plugin* would be a good solution, but sadly I don't have the cycles to do that
- *avoid the Maven dependency* again, induces problems with a CI-flow

A partial, good-enough solution which I found is essentially a cheat, inspired by your options:
- I was lucky in the sense that indeed, it is a multi-module project, still I do not use anywhere the maven scope `provided`
- I've changed the scope of `org.checkerframework:checker` and `org.checkerframework:jdk8` to provided (and it still builds, yey! :+1:)
- I run the license plugin as `mvn license:aggregate-add-third-party -Dlicense.excludedScopes=provided` and will attach additionally the [definition of the provided scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html), essentially stating that it is a dependency which is out-of-scope for licensing questions.

Thanks again for the answer, will keep the link to this issue, maybe I will have to use all the info in it eventually :)

**Comment by mernst** [comment]
Great, I'm glad this worked out for you.  Using the `provided` scope is a clever trick.  I wonder whether I should put a note about this in the manual.  For now we'll hope that people find this issue.  If you end up enhancing your solution, please let us know.

The checkerframework-maven-plugin that you found on Maven Central is obsolete and has been replaced by the new instructions in the manual that do not require use of a separate plugin.  I'm always loathe to remove historical artifacts, but maybe we should do so in order to avoid confusion from users who stumble across it.

Thanks again for raising the issue and for providing your solution.
