### ISSUE TITLE
NullnessAnnotatedTypeFactory missing implicit nullness qualifier descriptions

### ISSUE THREAD

**Issue by chagmed** [typetools/checker-framework#878]
Section 3.3.1 of the manual states

> For a complete description of all implicit nullness qualifiers, see the Javadoc for NullnessAnnotatedTypeFactory

The javadocs for [NullnessAnnotatedTypeFactory](http://types.cs.washington.edu/checker-framework/current/api/org/checkerframework/checker/nullness/NullnessAnnotatedTypeFactory.html) in fact don't provide a description of all implicit nullness qualifiers.

It would be helpful to provide full descriptions of all such qualifiers in both the manual and in the associated Javadocs.

**Comment by mernst** [comment]
All qualifiers are fully described in the manual.  I've adjusted the manual to refer to "implicitly-added nullness qualifiers" rather than "implicit nullness qualifiers", because I think the latter was confusing.

Do you have a specific question about the rules for which expressions are implicitly qualified as non-null?  It's primarily "new" expressions.
