### ISSUE TITLE
What is the semantics of @TargetLocation meta-annotation?

### ISSUE THREAD

**Issue by topnessman** [typetools/checker-framework#975]
I'm working on enforcing `@TargetLocation` meta-annotation, and this is the pull request I made against oppop: [#26](https://github.com/opprop/checker-framework/pull/26). I have some questions about the meaning of `@TargetLocation`: should it only enforce a certain annotation cannot be EXPLICITLY written on locations other than the declared locations in its `@TargetLocation` meta-annotation or does it refer to any uses of that annotation, including explicit-use/defaulted/implicit?

Personally I vote for the latter one based on this: 

Take Generic Universe Type system as an example. 
We say `@Bottom` annotation can only be explicitly written on TypeUseLocation.EXPLICIT_LOWER_BOUND or TypeUseLocation.EXPLICIT_UPPER_BOUND. But our first-place purpose was to ensure that `@Bottom` cannot be used anywhere in the source code; if unfortunately we have to explicitly write it, explicit lower/upper bounds are the places where they are permitted to be written on. 

So this means what we are really interested in is to restrict the usage of `@Bottom` only on lower/upper bound(in the worst case, explicitly written out), BUT NOT explicitly use it or not. In other words, we are not caring about where they could be explicitly written, but to limit any usage location(maybe defaulted or implicit) to the locations specified in @TargetLocation meta-annotation.

If the above argument doesn't make sense to you, please skip this second issue:

The second issue is: some qualifiers like `@UnkownRegex` is declared with `@TargeteLocation({TypeUseLocation.EXPLICIT_LOWER_BOUND,
    TypeUseLocation.EXPLICIT_UPPER_BOUND})`, but at the same time it's annotated with `@DefaultQualifierInHierarchy`, meaning they will be defaulted way more other places than explicit lower/upper bound. As a result, this inconsistency between the `@TargetLocation` and  `@DefaultQualifierInHierarchy` causes lots of errors if `@TargetLocation` is enforced. Maybe it's not correct to specify  `@TargetLocation` on an annotation with `@DefaultQualifierInHierarchy`? 

Thank you!

**Comment by smillst** [comment]
`@TargetLocations` restrict where the annotation may be explicitly written.  A type system may default or infer the annotation in other locations.

>The second issue is: some qualifiers like `@UnkownRegex` is declared with `@TargeteLocation({TypeUseLocation.EXPLICIT_LOWER_BOUND,
    TypeUseLocation.EXPLICIT_UPPER_BOUND})`, but at the same time it's annotated with `@DefaultQualifierInHierarchy`, meaning they will be defaulted way more other places than explicit lower/upper bound. As a result, this inconsistency between the `@TargetLocation` and  `@DefaultQualifierInHierarchy` causes lots of errors if `@TargetLocation` is enforced.

Because a type system may default an annotation somewhere where it may not be explicitly written, this isn't an inconsistency.  A warning should not be issued if annotation appears in a location because it was defaulted or otherwise added by the type system.

**Comment by topnessman** [comment]
@smillst Thanks for your reply!
Then what's your purpose to allow an annotation can be defaulted on like FIELD location, but shouldn't be explicitly written? Or what's the actual difference?

**Comment by mernst** [comment]
Regarding the FIELD location, not every combination permitted by the annotations may make sense, so we don't have to justify every possibility.  But, your examples are well-motivated and they are strong arguments for the overall capability.  For example, top and bottom qualifiers can appear anywhere, but should only be explicitly written on explicit bounds; the capability ensures this.  (We wouldn't want a confusing error message to be issued whenever the type leaked anywhere else in the program.)  As another example, @UnknownRegex is the default and allowing people to write it explicitly in most locations would just clutter the code; the capability prevents that redundant clutter.

I don't understand your second question "Or what's the actual difference?"

**Comment by mernst** [comment]
To follow up a bit, it seems that there are two distinct concepts:
 * where an annotation may be written in source code.  This is indicated by `@TargetLocation`.
 * what types may be qualified by a given qualifier.  The Checker Framework has no convenient declarative mechanism for specifying this.

This issue is titled "What is the semantics of @TargetLocation meta-annotation?", but `@TargetLocation` is already unambiguously documented.
I think this issue is really one of the following requests:
 1. Please unify the two distinct concepts, so that `@TargetLocation` indicates them both.
 2. Please add a new annotation to represent the second concept above (what types may be qualified by a given qualifier).

I feel that the first option is undesirable.  The Checker Framework already forbids users from writing certain redundant qualifiers, for reasons of brevity and consistency.

The second option is a reasonable request, however.  I've opened issue #995 to track this issue.  Thanks for raising it!
